package com.app.dto;
import jakarta.validation.constraints.*; import lombok.*; import java.time.*; import java.util.*;
public final class SocietyDailyOperationsDtos {private SocietyDailyOperationsDtos(){}
 @Data public static class ChecklistTemplateRequest {@NotBlank @Size(max=180) private String title; @Size(max=1000) private String description; private Integer sortOrder;}
 @Data public static class ChecklistUpdateRequest {@NotNull private Boolean completed; @Size(max=1000) private String notes;}
 @Data @Builder public static class ChecklistItemDto {private Long templateId;private String title;private String description;private Integer sortOrder;private Long entryId;private Boolean completed;private String notes;private String completedBy;private LocalDateTime completedAt;}
 @Data public static class IncidentRequest {@NotBlank @Size(max=180) private String title;@NotBlank @Size(max=2000) private String description;@NotBlank private String severity;@Size(max=255) private String location;@NotNull private LocalDateTime occurredAt;@Size(max=2000) private String immediateAction;private Boolean sensitive;}
 @Data public static class IncidentUpdateRequest {@NotBlank private String status;@Size(max=2000) private String followUp;}
 @Data @Builder public static class IncidentDto {private Long id;private String incidentNumber;private String title;private String description;private String severity;private String location;private LocalDateTime occurredAt;private String status;private String immediateAction;private String followUp;private Boolean sensitive;private String createdBy;private LocalDateTime closedAt;}
 @Data public static class InspectionRequest {@NotBlank @Size(max=180) private String title;@Size(max=255) private String location;private LocalDateTime scheduledFor;@Size(max=4000) private String checklist;}
 @Data public static class InspectionCompleteRequest {@NotBlank private String result;@Size(max=2000) private String notes;@Size(max=2000) private String failureAction;private Long workOrderId;}
 @Data @Builder public static class InspectionDto {private Long id;private String title;private String location;private LocalDateTime scheduledFor;private LocalDateTime completedAt;private String result;private String checklist;private String notes;private String failureAction;private Long workOrderId;private String completedBy;}
 @Data public static class HandoverRequest {@NotNull private LocalDate shiftDate;@NotBlank @Size(max=100) private String shiftName;@Size(max=3000) private String openItems;@Size(max=2000) private String incidents;@Size(max=2000) private String expectedVisitors;@Size(max=2000) private String assetsHandedOver;@Size(max=2000) private String equipmentStatus;@Size(max=1000) private String attendanceShortages;@Size(max=2000) private String notes;@Size(max=180) private String receiverName;}
 @Data @Builder public static class HandoverDto {private Long id;private LocalDate shiftDate;private String shiftName;private String openItems;private String incidents;private String expectedVisitors;private String assetsHandedOver;private String equipmentStatus;private String attendanceShortages;private String notes;private String sender;private String receiverName;private LocalDateTime acknowledgedAt;private String acknowledgedBy;private LocalDateTime createdAt;}
 @Data public static class ReportRequest {@NotNull private LocalDate reportDate;@Size(max=4000) private String summary;@Size(max=2000) private String nextDayPriorities;}
 @Data public static class AcknowledgeRequest {@Size(max=2000) private String comment;}
 @Data @Builder public static class DailyReportDto {private Long id;private LocalDate reportDate;private Integer revision;private String status;private String summary;private String nextDayPriorities;private Map<String,Object> snapshot;private String submittedBy;private LocalDateTime submittedAt;private String acknowledgedBy;private LocalDateTime acknowledgedAt;private String adminComment;}
 @Data @Builder public static class DashboardDto {private LocalDate date;private long attendanceRecorded;private long present;private long absent;private long openWorkOrders;private long overdueWorkOrders;private long openComplaints;private long openIncidents;private long inspectionsDue;private long inspectionsFailed;private long handovers;private long checklistTotal;private long checklistCompleted;private String reportStatus;private List<DailyReportDto> recentReports;}
}
