package com.app.controller;
import com.app.dto.SocietyDailyOperationsDtos.*; import com.app.security.UserPrincipal; import com.app.service.SocietyDailyOperationsService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/society/daily-operations") @RequiredArgsConstructor public class SocietyDailyOperationsController {private final SocietyDailyOperationsService service;
 @GetMapping("/dashboard") public DashboardDto dashboard(@AuthenticationPrincipal UserPrincipal p,@RequestParam LocalDate date){return service.dashboard(p.getAccountId(),date);}
 @GetMapping("/checklist") public List<ChecklistItemDto> checklist(@AuthenticationPrincipal UserPrincipal p,@RequestParam LocalDate date){return service.checklist(p.getAccountId(),date);}
 @PostMapping("/checklist/templates") public ChecklistItemDto template(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody ChecklistTemplateRequest r){return service.createTemplate(p.getAccountId(),p.getUserId(),r);}
 @DeleteMapping("/checklist/templates/{id}") public void disable(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id){service.disableTemplate(p.getAccountId(),p.getUserId(),id);}
 @PutMapping("/checklist/{id}") public ChecklistItemDto checklistUpdate(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id,@RequestParam LocalDate date,@Valid @RequestBody ChecklistUpdateRequest r){return service.updateChecklist(p.getAccountId(),p.getUserId(),id,date,r);}
 @GetMapping("/incidents") public List<IncidentDto> incidents(@AuthenticationPrincipal UserPrincipal p){return service.listIncidents(p.getAccountId());}@PostMapping("/incidents") public IncidentDto incident(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody IncidentRequest r){return service.createIncident(p.getAccountId(),p.getUserId(),r);}@PutMapping("/incidents/{id}") public IncidentDto incidentUpdate(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id,@Valid @RequestBody IncidentUpdateRequest r){return service.updateIncident(p.getAccountId(),p.getUserId(),id,r);}
 @GetMapping("/inspections") public List<InspectionDto> inspections(@AuthenticationPrincipal UserPrincipal p){return service.listInspections(p.getAccountId());}@PostMapping("/inspections") public InspectionDto inspection(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody InspectionRequest r){return service.createInspection(p.getAccountId(),p.getUserId(),r);}@PutMapping("/inspections/{id}/complete") public InspectionDto inspectionComplete(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id,@Valid @RequestBody InspectionCompleteRequest r){return service.completeInspection(p.getAccountId(),p.getUserId(),id,r);}
 @GetMapping("/handovers") public List<HandoverDto> handovers(@AuthenticationPrincipal UserPrincipal p){return service.listHandovers(p.getAccountId());}@PostMapping("/handovers") public HandoverDto handover(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody HandoverRequest r){return service.createHandover(p.getAccountId(),p.getUserId(),r);}@PostMapping("/handovers/{id}/acknowledge") public HandoverDto handoverAck(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id){return service.acknowledgeHandover(p.getAccountId(),p.getUserId(),id);}
 @GetMapping("/reports") public List<DailyReportDto> reports(@AuthenticationPrincipal UserPrincipal p){return service.listReports(p.getAccountId());}@PostMapping("/reports/draft") public DailyReportDto draft(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody ReportRequest r){return service.saveReport(p.getAccountId(),p.getUserId(),r,false);}@PostMapping("/reports/submit") public DailyReportDto submit(@AuthenticationPrincipal UserPrincipal p,@Valid @RequestBody ReportRequest r){return service.saveReport(p.getAccountId(),p.getUserId(),r,true);}@PostMapping("/reports/{id}/acknowledge") public DailyReportDto acknowledge(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id,@Valid @RequestBody AcknowledgeRequest r){return service.acknowledgeReport(p.getAccountId(),p.getUserId(),id,r);}@PostMapping("/reports/{id}/reopen") public DailyReportDto reopen(@AuthenticationPrincipal UserPrincipal p,@PathVariable Long id){return service.reopenReport(p.getAccountId(),p.getUserId(),id);}
}
