package com.app.controller;
import com.app.dto.SocietyOperationsReportDtos.*;import com.app.security.UserPrincipal;import com.app.service.SocietyOperationsReportService;import lombok.RequiredArgsConstructor;import org.springframework.core.io.ByteArrayResource;import org.springframework.http.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;
@RestController @RequestMapping("/society/operations-reports") @RequiredArgsConstructor public class SocietyOperationsReportController {private final SocietyOperationsReportService service;
 @GetMapping("/agency-compliance") public AgencyComplianceReport agency(@AuthenticationPrincipal UserPrincipal p,@RequestParam int year,@RequestParam int month){return service.agencyCompliance(p.getAccountId(),year,month);}
 @GetMapping("/supervisor-performance") public SupervisorPerformanceReport supervisor(@AuthenticationPrincipal UserPrincipal p,@RequestParam LocalDate from,@RequestParam LocalDate to){return service.supervisorPerformance(p.getAccountId(),from,to);}
 @GetMapping("/agency-compliance/export") public ResponseEntity<ByteArrayResource> agencyExport(@AuthenticationPrincipal UserPrincipal p,@RequestParam int year,@RequestParam int month,@RequestParam String format){return file(service.exportAgency(p.getAccountId(),year,month,format));}
 @GetMapping("/supervisor-performance/export") public ResponseEntity<ByteArrayResource> supervisorExport(@AuthenticationPrincipal UserPrincipal p,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam String format){return file(service.exportSupervisor(p.getAccountId(),from,to,format));}
 private ResponseEntity<ByteArrayResource> file(ExportFile f){return ResponseEntity.ok().contentType(MediaType.parseMediaType(f.contentType())).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+f.filename()+"\"").contentLength(f.content().length).body(new ByteArrayResource(f.content()));}
}
