package com.app.service;
import com.app.dto.SocietyRosterDtos.*; import com.app.entity.*; import com.app.exception.*; import com.app.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class SocietyRosterService {
 private final AccountRepository accounts; private final SocietyShiftRepository shifts; private final SocietyRosterAssignmentRepository assignments; private final SocietyStaffRepository staff; private final SocietyAgencyWorkerRepository workers;
 @Transactional(readOnly=true) public List<ShiftDto> shifts(Long accountId){society(accountId);return shifts.findByAccountIdAndActiveTrueOrderByStartTimeAsc(accountId).stream().map(this::shiftDto).toList();}
 @Transactional public ShiftDto createShift(Long accountId,ShiftRequest r){Account a=society(accountId);return shiftDto(shifts.save(SocietyShift.builder().account(a).name(r.getName().trim()).startTime(r.getStartTime()).endTime(r.getEndTime()).graceMinutes(r.getGraceMinutes()==null?0:r.getGraceMinutes()).build()));}
 @Transactional public ShiftDto updateShift(Long accountId,Long id,ShiftRequest r){SocietyShift s=shift(accountId,id);s.setName(r.getName().trim());s.setStartTime(r.getStartTime());s.setEndTime(r.getEndTime());s.setGraceMinutes(r.getGraceMinutes()==null?0:r.getGraceMinutes());return shiftDto(shifts.save(s));}
 @Transactional public void deleteShift(Long accountId,Long id){SocietyShift s=shift(accountId,id);boolean used=assignments.findByAccountIdAndActiveTrueOrderByPostNameAsc(accountId).stream().anyMatch(a->a.getShift().getId().equals(id));if(used)throw new ValidationException("Deactivate roster assignments before removing this shift");s.setActive(false);shifts.save(s);}
 @Transactional(readOnly=true) public List<AssignmentDto> roster(Long accountId){society(accountId);return assignments.findByAccountIdAndActiveTrueOrderByPostNameAsc(accountId).stream().map(this::assignmentDto).toList();}
 @Transactional public AssignmentDto assign(Long accountId,AssignmentRequest r){Account a=society(accountId);validate(r);SocietyShift shift=shift(accountId,r.getShiftId());SocietyStaff member=r.getStaffId()==null?null:staff.findByAccountIdAndIdAndActiveTrue(accountId,r.getStaffId()).orElseThrow(()->new ResourceNotFoundException("Staff member not found"));SocietyAgencyWorker worker=r.getAgencyWorkerId()==null?null:workers.findByAccountIdAndIdAndActiveTrue(accountId,r.getAgencyWorkerId()).orElseThrow(()->new ResourceNotFoundException("Agency worker not found"));return assignmentDto(assignments.save(SocietyRosterAssignment.builder().account(a).shift(shift).staff(member).agencyWorker(worker).postName(r.getPostName().trim()).effectiveFrom(r.getEffectiveFrom()).effectiveTo(r.getEffectiveTo()).build()));}
 @Transactional public void removeAssignment(Long accountId,Long id){society(accountId);SocietyRosterAssignment a=assignments.findByAccountIdAndIdAndActiveTrue(accountId,id).orElseThrow(()->new ResourceNotFoundException("Roster assignment not found"));a.setActive(false);assignments.save(a);}
 private void validate(AssignmentRequest r){if((r.getStaffId()==null)==(r.getAgencyWorkerId()==null))throw new ValidationException("Select exactly one staff member or agency worker");if(r.getEffectiveTo()!=null&&r.getEffectiveTo().isBefore(r.getEffectiveFrom()))throw new ValidationException("Effective end cannot be before start");}
 private Account society(Long id){return accounts.findById(id).filter(a->a.getAccountType()==AccountType.SOCIETY&&Boolean.TRUE.equals(a.getActive())).orElseThrow(()->new ResourceNotFoundException("Society not found"));} private SocietyShift shift(Long accountId,Long id){society(accountId);return shifts.findByAccountIdAndIdAndActiveTrue(accountId,id).orElseThrow(()->new ResourceNotFoundException("Shift not found"));}
 private ShiftDto shiftDto(SocietyShift s){return ShiftDto.builder().id(s.getId()).name(s.getName()).startTime(s.getStartTime()).endTime(s.getEndTime()).graceMinutes(s.getGraceMinutes()).build();}
 private AssignmentDto assignmentDto(SocietyRosterAssignment a){boolean direct=a.getStaff()!=null;return AssignmentDto.builder().id(a.getId()).shiftId(a.getShift().getId()).shiftName(a.getShift().getName()).staffId(direct?a.getStaff().getId():null).agencyWorkerId(direct?null:a.getAgencyWorker().getId()).assigneeName(direct?a.getStaff().getStaffName():a.getAgencyWorker().getWorkerName()).assigneeType(direct?"DIRECT":"AGENCY").postName(a.getPostName()).effectiveFrom(a.getEffectiveFrom()).effectiveTo(a.getEffectiveTo()).build();}
}
