package com.app.service;
import com.app.dto.SocietyWorkOrderDtos.*; import com.app.entity.*; import com.app.exception.*; import com.app.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class SocietyWorkOrderService {
 private static final Set<String> CATEGORIES=Set.of("ELECTRICAL","PLUMBING","LIFT","CLEANING","SECURITY","CIVIL","GARDENING","FIRE_SAFETY","OTHER");
 private static final Set<String> SOURCES=Set.of("SUPERVISOR","ADMIN","RESIDENT_COMPLAINT","INSPECTION","PREVENTIVE_SCHEDULE","INCIDENT");
 private static final Set<String> PRIORITIES=Set.of("LOW","NORMAL","HIGH","EMERGENCY"); private static final Set<String> UPDATE_STATUSES=Set.of("IN_PROGRESS","BLOCKED","ASSIGNED");
 private final AccountRepository accounts; private final UserRepository users; private final SocietyWorkOrderRepository orders; private final SocietyWorkAssignmentRepository assignments; private final SocietyWorkUpdateRepository updates; private final SocietyStaffRepository staff; private final SocietyAgencyRepository agencies; private final SupplierRepository vendors; private final SocietyAuditEventRepository audit;
 @Transactional(readOnly=true) public List<WorkOrderDto> list(Long accountId){society(accountId);return orders.findByAccountIdOrderByCreatedAtDesc(accountId).stream().map(x->dto(x,false)).toList();}
 @Transactional(readOnly=true) public WorkOrderDto get(Long accountId,Long id){return dto(order(accountId,id),true);}
 @Transactional public WorkOrderDto create(Long accountId,Long userId,CreateRequest r){Account a=society(accountId);User u=user(userId);String category=choice(r.getCategory(),CATEGORIES,"category"),source=choice(r.getSource(),SOURCES,"source"),priority=choice(r.getPriority(),PRIORITIES,"priority");if(r.getDueAt()!=null&&r.getPlannedStart()!=null&&r.getDueAt().isBefore(r.getPlannedStart()))throw new ValidationException("Due date cannot be before planned start");long sequence=orders.countByAccountId(accountId)+1;String number="WO-"+String.format("%05d",sequence);SocietyWorkOrder saved=orders.save(SocietyWorkOrder.builder().account(a).workOrderNumber(number).title(r.getTitle().trim()).description(clean(r.getDescription())).category(category).source(source).location(clean(r.getLocation())).priority(priority).plannedStart(r.getPlannedStart()).dueAt(r.getDueAt()).estimatedCost(r.getEstimatedCost()).createdBy(u).build());event(saved,u,"CREATED",null,"OPEN","Work order created");return dto(saved,true);}
 @Transactional public WorkOrderDto assign(Long accountId,Long userId,Long id,AssignmentRequest r){SocietyWorkOrder w=order(accountId,id);ensureMutable(w);int count=(r.getStaffId()==null?0:1)+(r.getAgencyId()==null?0:1)+(r.getVendorId()==null?0:1);if(count!=1)throw new ValidationException("Select exactly one staff member, agency, or vendor");assignments.findByAccountIdAndWorkOrderIdAndActiveTrue(accountId,id).forEach(x->{x.setActive(false);assignments.save(x);});SocietyWorkAssignment a=SocietyWorkAssignment.builder().account(w.getAccount()).workOrder(w).assignedBy(user(userId)).staff(r.getStaffId()==null?null:staff.findByAccountIdAndIdAndActiveTrue(accountId,r.getStaffId()).orElseThrow(()->new ResourceNotFoundException("Staff member not found"))).agency(r.getAgencyId()==null?null:agencies.findByAccountIdAndIdAndActiveTrue(accountId,r.getAgencyId()).orElseThrow(()->new ResourceNotFoundException("Agency not found"))).vendor(r.getVendorId()==null?null:vendors.findByAccountIdAndIdAndActiveTrue(accountId,r.getVendorId()).orElseThrow(()->new ResourceNotFoundException("Vendor not found"))).build();assignments.save(a);String old=w.getStatus();w.setStatus("ASSIGNED");orders.save(w);event(w,a.getAssignedBy(),"ASSIGNED",old,"ASSIGNED",assignee(a));return dto(w,true);}
 @Transactional public WorkOrderDto update(Long accountId,Long userId,Long id,UpdateRequest r){SocietyWorkOrder w=order(accountId,id);ensureMutable(w);String next=r.getStatus()==null?w.getStatus():choice(r.getStatus(),UPDATE_STATUSES,"update status");if("IN_PROGRESS".equals(next)&&w.getActualStart()==null)w.setActualStart(LocalDateTime.now());String old=w.getStatus();w.setStatus(next);orders.save(w);event(w,user(userId),"PROGRESS",old,next,r.getNotes().trim());return dto(w,true);}
 @Transactional public WorkOrderDto complete(Long accountId,Long userId,Long id,CompleteRequest r){SocietyWorkOrder w=order(accountId,id);ensureMutable(w);if(assignments.findByAccountIdAndWorkOrderIdAndActiveTrue(accountId,id).isEmpty())throw new ValidationException("Assign the work order before completing it");String old=w.getStatus();w.setStatus("COMPLETED");w.setCompletedAt(LocalDateTime.now());w.setCompletionNotes(r.getCompletionNotes().trim());w.setActualCost(r.getActualCost());orders.save(w);event(w,user(userId),"COMPLETED",old,"COMPLETED",w.getCompletionNotes());return dto(w,true);}
 @Transactional public WorkOrderDto verify(Long accountId,Long userId,Long id,VerifyRequest r){SocietyWorkOrder w=order(accountId,id);if(!"COMPLETED".equals(w.getStatus()))throw new ValidationException("Only completed work can be verified");User u=user(userId);w.setStatus("VERIFIED");w.setVerifiedBy(u);w.setVerifiedAt(LocalDateTime.now());orders.save(w);event(w,u,"VERIFIED","COMPLETED","VERIFIED",clean(r.getNotes()));return dto(w,true);}
 @Transactional public WorkOrderDto reopen(Long accountId,Long userId,Long id,VerifyRequest r){SocietyWorkOrder w=order(accountId,id);if(!Set.of("COMPLETED","VERIFIED").contains(w.getStatus()))throw new ValidationException("Only completed or verified work can be reopened");String old=w.getStatus();w.setStatus("IN_PROGRESS");w.setCompletedAt(null);w.setVerifiedAt(null);w.setVerifiedBy(null);orders.save(w);event(w,user(userId),"REOPENED",old,"IN_PROGRESS",clean(r.getNotes()));return dto(w,true);}
 private void event(SocietyWorkOrder w,User u,String type,String old,String next,String notes){updates.save(SocietyWorkUpdate.builder().account(w.getAccount()).workOrder(w).createdBy(u).updateType(type).previousStatus(old).newStatus(next).notes(notes).build());audit.save(SocietyAuditEvent.builder().account(w.getAccount()).actor(u).action("WORK_ORDER_"+type).entityType("WORK_ORDER").entityId(w.getId()).details("number="+w.getWorkOrderNumber()+(notes==null?"":"; "+notes)).build());}
 private WorkOrderDto dto(SocietyWorkOrder w,boolean history){List<AssignmentDto> as=assignments.findByAccountIdAndWorkOrderIdAndActiveTrue(w.getAccount().getId(),w.getId()).stream().map(this::assignmentDto).toList();List<UpdateDto> us=history?updates.findByAccountIdAndWorkOrderIdOrderByCreatedAtAsc(w.getAccount().getId(),w.getId()).stream().map(x->UpdateDto.builder().id(x.getId()).updateType(x.getUpdateType()).previousStatus(x.getPreviousStatus()).newStatus(x.getNewStatus()).notes(x.getNotes()).createdBy(x.getCreatedBy().getName()).createdAt(x.getCreatedAt()).build()).toList():List.of();return WorkOrderDto.builder().id(w.getId()).workOrderNumber(w.getWorkOrderNumber()).title(w.getTitle()).description(w.getDescription()).category(w.getCategory()).source(w.getSource()).location(w.getLocation()).priority(w.getPriority()).status(w.getStatus()).plannedStart(w.getPlannedStart()).dueAt(w.getDueAt()).actualStart(w.getActualStart()).completedAt(w.getCompletedAt()).completionNotes(w.getCompletionNotes()).estimatedCost(w.getEstimatedCost()).actualCost(w.getActualCost()).verifiedBy(w.getVerifiedBy()==null?null:w.getVerifiedBy().getName()).verifiedAt(w.getVerifiedAt()).createdBy(w.getCreatedBy().getName()).createdAt(w.getCreatedAt()).overdue(w.getDueAt()!=null&&w.getDueAt().isBefore(LocalDateTime.now())&&!Set.of("COMPLETED","VERIFIED","CANCELLED").contains(w.getStatus())).assignments(as).updates(us).build();}
 private AssignmentDto assignmentDto(SocietyWorkAssignment a){String type=a.getStaff()!=null?"STAFF":a.getAgency()!=null?"AGENCY":"VENDOR";Long id=a.getStaff()!=null?a.getStaff().getId():a.getAgency()!=null?a.getAgency().getId():a.getVendor().getId();String name=a.getStaff()!=null?a.getStaff().getStaffName():a.getAgency()!=null?a.getAgency().getName():a.getVendor().getSupplierName();return AssignmentDto.builder().id(a.getId()).assigneeType(type).assigneeId(id).assigneeName(name).assignedAt(a.getAssignedAt()).build();}
 private void ensureMutable(SocietyWorkOrder w){if(Set.of("VERIFIED","CANCELLED").contains(w.getStatus()))throw new ValidationException("This work order is closed");} private SocietyWorkOrder order(Long aid,Long id){society(aid);return orders.findByAccountIdAndId(aid,id).orElseThrow(()->new ResourceNotFoundException("Work order not found"));} private Account society(Long id){return accounts.findById(id).filter(a->a.getAccountType()==AccountType.SOCIETY&&Boolean.TRUE.equals(a.getActive())).orElseThrow(()->new ResourceNotFoundException("Society not found"));}private User user(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found"));}private String choice(String v,Set<String> allowed,String field){String x=v==null?"":v.trim().toUpperCase();if(!allowed.contains(x))throw new ValidationException("Invalid "+field);return x;}private String clean(String s){return s==null||s.isBlank()?null:s.trim();}private String assignee(SocietyWorkAssignment a){return "Assigned to "+assignmentDto(a).getAssigneeName();}
}
