package com.app.service;
import com.app.dto.SocietyComplaintDtos.*; import com.app.dto.SocietyWorkOrderDtos; import com.app.entity.*; import com.app.exception.*; import com.app.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class SocietyComplaintService {
 private static final Set<String> STATUSES=Set.of("OPEN","ACKNOWLEDGED","IN_PROGRESS","RESOLVED","CLOSED"), PRIORITIES=Set.of("LOW","NORMAL","HIGH","EMERGENCY"), CATEGORIES=Set.of("ELECTRICAL","PLUMBING","LIFT","CLEANING","SECURITY","CIVIL","GARDENING","FIRE_SAFETY","OTHER");
 private final AccountRepository accounts; private final UserRepository users; private final FlatRepository flats; private final AccountUserMembershipRepository memberships; private final SocietyStaffAccessRepository staffAccess; private final SocietyComplaintRepository complaints; private final SocietyComplaintUpdateRepository updates; private final SocietyWorkOrderRepository orders; private final SocietyWorkOrderService workOrders; private final SocietyAuditEventRepository audit;
 @Transactional(readOnly=true) public List<ComplaintDto> list(Long accountId,Long userId){society(accountId);boolean ops=operational(accountId,userId);List<SocietyComplaint> rows=ops?complaints.findByAccountIdOrderByCreatedAtDesc(accountId):complaints.findByAccountIdAndComplainantIdOrderByCreatedAtDesc(accountId,userId);return rows.stream().map(x->dto(x,false,ops)).toList();}
 @Transactional(readOnly=true) public ComplaintDto get(Long accountId,Long userId,Long id){SocietyComplaint c=complaint(accountId,id);boolean ops=operational(accountId,userId);if(!ops&&!c.getComplainant().getId().equals(userId))throw new ResourceNotFoundException("Complaint not found");return dto(c,true,ops);}
 @Transactional public ComplaintDto create(Long accountId,Long userId,CreateRequest r){Account a=society(accountId);User u=user(userId);Flat f=flats.findByAccountIdAndIdAndActiveTrue(accountId,r.getFlatId()).orElseThrow(()->new ResourceNotFoundException("Flat not found"));if(!operational(accountId,userId)&&!ownsFlat(accountId,userId,f))throw new ValidationException("You can raise complaints only for your approved flat");String priority=choice(r.getPriority(),PRIORITIES,"priority"),category=choice(r.getCategory(),CATEGORIES,"category");String number="CMP-"+String.format("%05d",complaints.countByAccountId(accountId)+1);SocietyComplaint c=complaints.save(SocietyComplaint.builder().account(a).complaintNumber(number).flat(f).complainant(u).complainantName(u.getName()).title(r.getTitle().trim()).description(r.getDescription().trim()).category(category).priority(priority).build());record(c,u,"OPEN","Complaint raised",true,"COMPLAINT_CREATED");return dto(c,true,operational(accountId,userId));}
 @Transactional public ComplaintDto update(Long accountId,Long userId,Long id,UpdateRequest r){SocietyComplaint c=complaint(accountId,id);boolean ops=operational(accountId,userId);if(!ops&&!c.getComplainant().getId().equals(userId))throw new ResourceNotFoundException("Complaint not found");if("CLOSED".equals(c.getStatus()))throw new ValidationException("Closed complaints cannot be updated");String status=c.getStatus();boolean visible=true;if(ops){if(r.getStatus()!=null)status=choice(r.getStatus(),STATUSES,"status");visible=!Boolean.FALSE.equals(r.getResidentVisible());}else if(r.getStatus()!=null||Boolean.FALSE.equals(r.getResidentVisible()))throw new ValidationException("Residents cannot change status or add internal notes");if("ACKNOWLEDGED".equals(status)&&c.getAcknowledgedAt()==null)c.setAcknowledgedAt(LocalDateTime.now());if(Set.of("RESOLVED","CLOSED").contains(status)&&c.getResolvedAt()==null)c.setResolvedAt(LocalDateTime.now());c.setStatus(status);complaints.save(c);record(c,user(userId),status,r.getNotes().trim(),visible,"COMPLAINT_UPDATED");return dto(c,true,ops);}
 @Transactional public ComplaintDto convert(Long accountId,Long userId,Long id,ConvertRequest r){if(!operational(accountId,userId))throw new ValidationException("Only society operations staff can convert complaints");SocietyComplaint c=complaint(accountId,id);if(c.getWorkOrder()!=null)throw new ValidationException("Complaint already has a work order");SocietyWorkOrderDtos.CreateRequest wr=new SocietyWorkOrderDtos.CreateRequest();wr.setTitle(c.getTitle());wr.setDescription(c.getDescription());wr.setCategory(c.getCategory());wr.setSource("RESIDENT_COMPLAINT");wr.setLocation(c.getFlat().getBlockName()+" / "+c.getFlat().getFlatNumber());wr.setPriority(c.getPriority());wr.setDueAt(r.getDueAt());var created=workOrders.create(accountId,userId,wr);if(r.getStaffId()!=null||r.getAgencyId()!=null||r.getVendorId()!=null){SocietyWorkOrderDtos.AssignmentRequest ar=new SocietyWorkOrderDtos.AssignmentRequest();ar.setStaffId(r.getStaffId());ar.setAgencyId(r.getAgencyId());ar.setVendorId(r.getVendorId());created=workOrders.assign(accountId,userId,created.getId(),ar);}c.setWorkOrder(orders.findByAccountIdAndId(accountId,created.getId()).orElseThrow());c.setStatus("IN_PROGRESS");if(c.getAcknowledgedAt()==null)c.setAcknowledgedAt(LocalDateTime.now());complaints.save(c);record(c,user(userId),"IN_PROGRESS","Converted to "+created.getWorkOrderNumber(),true,"COMPLAINT_CONVERTED");return dto(c,true,true);}
 private void record(SocietyComplaint c,User u,String status,String notes,boolean visible,String action){updates.save(SocietyComplaintUpdate.builder().account(c.getAccount()).complaint(c).createdBy(u).status(status).notes(notes).residentVisible(visible).build());audit.save(SocietyAuditEvent.builder().account(c.getAccount()).actor(u).action(action).entityType("COMPLAINT").entityId(c.getId()).details("number="+c.getComplaintNumber()+"; "+notes).build());}
 private ComplaintDto dto(SocietyComplaint c,boolean history,boolean ops){List<UpdateDto> us=history?updates.findByAccountIdAndComplaintIdOrderByCreatedAtAsc(c.getAccount().getId(),c.getId()).stream().filter(x->ops||Boolean.TRUE.equals(x.getResidentVisible())).map(x->UpdateDto.builder().id(x.getId()).status(x.getStatus()).notes(x.getNotes()).residentVisible(Boolean.TRUE.equals(x.getResidentVisible())).createdBy(x.getCreatedBy().getName()).createdAt(x.getCreatedAt()).build()).toList():List.of();return ComplaintDto.builder().id(c.getId()).complaintNumber(c.getComplaintNumber()).flatId(c.getFlat().getId()).flat(c.getFlat().getBlockName()+" / "+c.getFlat().getFlatNumber()).complainantName(c.getComplainantName()).title(c.getTitle()).description(c.getDescription()).category(c.getCategory()).priority(c.getPriority()).status(c.getStatus()).workOrderId(c.getWorkOrder()==null?null:c.getWorkOrder().getId()).workOrderNumber(c.getWorkOrder()==null?null:c.getWorkOrder().getWorkOrderNumber()).acknowledgedAt(c.getAcknowledgedAt()).resolvedAt(c.getResolvedAt()).createdAt(c.getCreatedAt()).updates(us).build();}
 private boolean operational(Long aid,Long uid){Account a=society(aid);if(a.getUser().getId().equals(uid))return true;return memberships.findByAccountIdAndUserIdAndActiveTrue(aid,uid).map(m->Set.of(UserRole.ADMIN,UserRole.SUPERVISOR,UserRole.TREASURER).contains(m.getRole())).orElse(false)||staffAccess.findByAccountIdAndUserIdAndStatus(aid,uid,StaffAccessStatus.ACTIVE).isPresent();}
 private boolean ownsFlat(Long aid,Long uid,Flat f){return memberships.findByAccountIdAndUserIdAndActiveTrue(aid,uid).map(m->m.getRequestedBlockName()!=null&&m.getRequestedFlatNumber()!=null&&f.getBlockName().equalsIgnoreCase(m.getRequestedBlockName())&&f.getFlatNumber().equalsIgnoreCase(m.getRequestedFlatNumber())).orElse(false);}
 private SocietyComplaint complaint(Long aid,Long id){society(aid);return complaints.findByAccountIdAndId(aid,id).orElseThrow(()->new ResourceNotFoundException("Complaint not found"));}private Account society(Long id){return accounts.findById(id).filter(a->a.getAccountType()==AccountType.SOCIETY&&Boolean.TRUE.equals(a.getActive())).orElseThrow(()->new ResourceNotFoundException("Society not found"));}private User user(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found"));}private String choice(String v,Set<String> allowed,String field){String x=v==null?"":v.trim().toUpperCase();if(!allowed.contains(x))throw new ValidationException("Invalid "+field);return x;}
}
