package com.app.service;
import com.app.dto.SocietyNotificationDto; import com.app.entity.*; import com.app.exception.*; import com.app.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class SocietyNotificationService {private final AccountRepository accounts;private final UserRepository users;private final AccountUserMembershipRepository memberships;private final SocietyStaffAccessRepository staffAccess;private final SocietyWorkOrderRepository orders;private final SocietyNotificationRepository notifications;
 @Transactional public List<SocietyNotificationDto> inbox(Long accountId,Long userId){Account a=authorized(accountId,userId);User u=users.findById(userId).orElseThrow(()->new ResourceNotFoundException("User not found"));for(SocietyWorkOrder w:orders.findByAccountIdOrderByCreatedAtDesc(accountId)){if(Set.of("COMPLETED","VERIFIED","CANCELLED").contains(w.getStatus()))continue;if(w.getDueAt()!=null&&w.getDueAt().isBefore(LocalDateTime.now()))ensure(a,u,w,"WORK_ORDER_OVERDUE","OVERDUE:"+w.getId(),"Work order overdue",w.getWorkOrderNumber()+" · "+w.getTitle()+" is overdue","EMERGENCY".equals(w.getPriority())?"EMERGENCY":"HIGH");if(Set.of("HIGH","EMERGENCY").contains(w.getPriority()))ensure(a,u,w,"WORK_ORDER_PRIORITY","PRIORITY:"+w.getId(),w.getPriority()+" priority work",w.getWorkOrderNumber()+" · "+w.getTitle()+" requires attention",w.getPriority());}return notifications.findByAccountIdAndRecipientIdOrderByCreatedAtDesc(accountId,userId).stream().map(this::dto).toList();}
 @Transactional(readOnly=true) public long unread(Long accountId,Long userId){authorized(accountId,userId);return notifications.countByAccountIdAndRecipientIdAndReadAtIsNull(accountId,userId);}
 @Transactional public SocietyNotificationDto read(Long accountId,Long userId,Long id){authorized(accountId,userId);SocietyNotification n=notifications.findByAccountIdAndRecipientIdAndId(accountId,userId,id).orElseThrow(()->new ResourceNotFoundException("Notification not found"));if(n.getReadAt()==null){n.setReadAt(LocalDateTime.now());notifications.save(n);}return dto(n);}
 @Transactional public void readAll(Long accountId,Long userId){authorized(accountId,userId);LocalDateTime now=LocalDateTime.now();notifications.findByAccountIdAndRecipientIdOrderByCreatedAtDesc(accountId,userId).stream().filter(x->x.getReadAt()==null).forEach(x->{x.setReadAt(now);notifications.save(x);});}
 private void ensure(Account a,User u,SocietyWorkOrder w,String type,String key,String title,String message,String priority){if(notifications.findByAccountIdAndRecipientIdAndDedupeKey(a.getId(),u.getId(),key).isPresent())return;notifications.save(SocietyNotification.builder().account(a).recipient(u).notificationType(type).entityType("WORK_ORDER").entityId(w.getId()).dedupeKey(key).title(title).message(message).priority(priority).build());}
 private Account authorized(Long aid,Long uid){Account a=accounts.findById(aid).filter(x->x.getAccountType()==AccountType.SOCIETY&&Boolean.TRUE.equals(x.getActive())).orElseThrow(()->new ResourceNotFoundException("Society not found"));if(a.getUser().getId().equals(uid))return a;boolean member=memberships.findByAccountIdAndUserIdAndActiveTrue(aid,uid).map(x->Set.of(UserRole.ADMIN,UserRole.SUPERVISOR,UserRole.TREASURER).contains(x.getRole())).orElse(false);boolean staff=staffAccess.findByAccountIdAndUserIdAndStatus(aid,uid,StaffAccessStatus.ACTIVE).isPresent();if(!member&&!staff)throw new ValidationException("Notifications are available only to society operations roles");return a;}
 private SocietyNotificationDto dto(SocietyNotification n){return SocietyNotificationDto.builder().id(n.getId()).notificationType(n.getNotificationType()).entityType(n.getEntityType()).entityId(n.getEntityId()).title(n.getTitle()).message(n.getMessage()).priority(n.getPriority()).readAt(n.getReadAt()).createdAt(n.getCreatedAt()).build();}
}
