package com.app.service;
import com.app.dto.SocietyAttendanceWorkflowDtos.*; import com.app.entity.*; import com.app.exception.*; import com.app.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class SocietyAttendanceWorkflowService {private final AccountRepository accounts;private final AccountUserMembershipRepository memberships;private final UserRepository users;private final SocietyAttendanceRepository attendance;private final SocietyAttendanceSheetRepository sheets;private final SocietyAttendanceCorrectionRepository corrections;
 @Transactional(readOnly=true) public void ensureEditable(Long accountId,LocalDate date){if(sheets.findByAccountIdAndAttendanceDate(accountId,date).map(x->!"DRAFT".equals(x.getStatus())).orElse(false))throw new ValidationException("Submitted attendance is locked; request a correction instead");}
 @Transactional(readOnly=true) public SheetDto status(Long accountId,LocalDate date){society(accountId);return sheets.findByAccountIdAndAttendanceDate(accountId,date).map(this::mapSheet).orElse(SheetDto.builder().attendanceDate(date).status("DRAFT").build());}
 @Transactional public SheetDto submit(Long accountId,Long userId,LocalDate date){Account a=society(accountId);if(attendance.findByAccountIdAndAttendanceDate(accountId,date).isEmpty())throw new ValidationException("Save attendance before submitting");SocietyAttendanceSheet s=sheets.findByAccountIdAndAttendanceDate(accountId,date).orElseGet(()->SocietyAttendanceSheet.builder().account(a).attendanceDate(date).build());if("LOCKED".equals(s.getStatus()))throw new ValidationException("Attendance sheet is locked");s.setStatus("SUBMITTED");s.setSubmittedBy(user(userId));s.setSubmittedAt(LocalDateTime.now());return mapSheet(sheets.save(s));}
 @Transactional public SheetDto lock(Long accountId,Long userId,LocalDate date){requireAdmin(accountId,userId);SocietyAttendanceSheet s=sheets.findByAccountIdAndAttendanceDate(accountId,date).orElseThrow(()->new ValidationException("Submit attendance before locking"));s.setStatus("LOCKED");s.setLockedBy(user(userId));s.setLockedAt(LocalDateTime.now());return mapSheet(sheets.save(s));}
 @Transactional public CorrectionDto request(Long accountId,Long userId,Long attendanceId,CorrectionRequest r){SocietyAttendance a=attendance.findByAccountIdAndId(accountId,attendanceId).orElseThrow(()->new ResourceNotFoundException("Attendance record not found"));if(sheets.findByAccountIdAndAttendanceDate(accountId,a.getAttendanceDate()).map(x->"DRAFT".equals(x.getStatus())).orElse(true))throw new ValidationException("Edit draft attendance directly");SocietyAttendanceCorrection c=corrections.save(SocietyAttendanceCorrection.builder().account(a.getAccount()).attendance(a).requestedBy(user(userId)).requestedStatus(r.getRequestedStatus()).requestedCheckIn(r.getRequestedCheckIn()).requestedCheckOut(r.getRequestedCheckOut()).reason(r.getReason().trim()).build());return map(c);}
 @Transactional(readOnly=true) public List<CorrectionDto> pending(Long accountId,Long userId){requireAdmin(accountId,userId);return corrections.findByAccountIdAndStatusOrderByCreatedAtDesc(accountId,"PENDING").stream().map(this::map).toList();}
 @Transactional public CorrectionDto approve(Long accountId,Long userId,Long id){requireAdmin(accountId,userId);SocietyAttendanceCorrection c=corrections.findByAccountIdAndId(accountId,id).orElseThrow(()->new ResourceNotFoundException("Correction request not found"));if(!"PENDING".equals(c.getStatus()))throw new ValidationException("Correction request is already reviewed");SocietyAttendance a=c.getAttendance();a.setStatus(c.getRequestedStatus());a.setCheckIn(c.getRequestedCheckIn());a.setCheckOut(c.getRequestedCheckOut());a.setRecordedBy(user(userId));attendance.save(a);c.setStatus("APPROVED");c.setReviewedBy(user(userId));c.setReviewedAt(LocalDateTime.now());return map(corrections.save(c));}
 private Account society(Long id){return accounts.findById(id).filter(a->a.getAccountType()==AccountType.SOCIETY).orElseThrow(()->new ResourceNotFoundException("Society not found"));}private User user(Long id){return users.findById(id).orElseThrow(()->new ValidationException("User not found"));}private void requireAdmin(Long accountId,Long userId){Account a=society(accountId);boolean ok=a.getUser().getId().equals(userId)&&a.getRole()==UserRole.ADMIN||memberships.findByAccountIdAndUserIdAndActiveTrue(accountId,userId).map(x->x.getRole()==UserRole.ADMIN).orElse(false);if(!ok)throw new ValidationException("Only a society admin can approve attendance");}
 private SheetDto mapSheet(SocietyAttendanceSheet s){return SheetDto.builder().attendanceDate(s.getAttendanceDate()).status(s.getStatus()).submittedAt(s.getSubmittedAt()).lockedAt(s.getLockedAt()).build();}private CorrectionDto map(SocietyAttendanceCorrection c){SocietyAttendance a=c.getAttendance();SocietyRosterAssignment r=a.getRosterAssignment();return CorrectionDto.builder().id(c.getId()).attendanceId(a.getId()).workerName(r.getStaff()!=null?r.getStaff().getStaffName():r.getAgencyWorker().getWorkerName()).attendanceDate(a.getAttendanceDate()).originalStatus(a.getStatus()).requestedStatus(c.getRequestedStatus()).requestedCheckIn(c.getRequestedCheckIn()).requestedCheckOut(c.getRequestedCheckOut()).reason(c.getReason()).status(c.getStatus()).createdAt(c.getCreatedAt()).build();}
}
