import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { societyAgencyAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'
import './AgencyList.css'

const emptyAgency = { name: '', serviceCategory: '', contactPerson: '', phone: '', email: '', contractStart: '', contractEnd: '', requiredHeadcount: 0 }
const emptyWorker = { workerName: '', workerCode: '', designation: '', mobile: '' }
const agencyValues = (x = emptyAgency) => Object.fromEntries(Object.keys(emptyAgency).map((key) => [key, x[key] ?? emptyAgency[key]]))
const workerValues = (x = emptyWorker) => Object.fromEntries(Object.keys(emptyWorker).map((key) => [key, x[key] ?? '']))

export const AgencyList = () => {
  const canManage = useAuthStore((s) => s.currentAccount?.role) === 'ADMIN'
  const [rows, setRows] = useState([]), [agency, setAgency] = useState(emptyAgency), [editingAgencyId, setEditingAgencyId] = useState(null), [workers, setWorkers] = useState({}), [editingWorkers, setEditingWorkers] = useState({}), [busy, setBusy] = useState(false), [agencyOpen, setAgencyOpen] = useState(false), [workerAgencyId, setWorkerAgencyId] = useState(null), [selectedAgencyId, setSelectedAgencyId] = useState(''), [activeAgencyId, setActiveAgencyId] = useState('all')
  const load = () => societyAgencyAPI.list().then(({ data }) => setRows(data || [])).catch((e) => toast.error(e.response?.data?.message || 'Unable to load agencies'))
  useEffect(() => { load() }, [])
  useEffect(() => {
    document.querySelectorAll('.agency-page > .report-panel').forEach((card, index) => {
      card.hidden = activeAgencyId !== 'all' && String(rows[index]?.id) !== String(activeAgencyId)
    })
  }, [activeAgencyId, rows])
  const resetAgency = () => { setAgency(emptyAgency); setEditingAgencyId(null); setAgencyOpen(false) }
  const saveAgency = async (e) => { e.preventDefault(); setBusy(true); const payload = { ...agency, contractStart: agency.contractStart || null, contractEnd: agency.contractEnd || null, requiredHeadcount: Number(agency.requiredHeadcount || 0) }; try { if (editingAgencyId) await societyAgencyAPI.update(editingAgencyId, payload); else await societyAgencyAPI.create(payload); toast.success(editingAgencyId ? 'Agency updated' : 'Agency added'); resetAgency(); load() } catch (x) { toast.error(x.response?.data?.message || 'Unable to save agency') } finally { setBusy(false) } }
  const editAgency = (item) => { setAgency(agencyValues(item)); setEditingAgencyId(item.id); setAgencyOpen(true) }
  const setWorker = (id, key, value) => setWorkers((v) => ({ ...v, [id]: { ...(v[id] || emptyWorker), [key]: value } }))
  const resetWorker = (id) => { setWorkers((v) => ({ ...v, [id]: emptyWorker })); setEditingWorkers((v) => ({ ...v, [id]: null })); setWorkerAgencyId(null) }
  const editWorker = (id, item) => { setWorkers((v) => ({ ...v, [id]: workerValues(item) })); setEditingWorkers((v) => ({ ...v, [id]: item.id })); setWorkerAgencyId(id) }
  const saveWorker = async (e, id) => { e.preventDefault(); const workerId = editingWorkers[id]; try { if (workerId) await societyAgencyAPI.updateWorker(id, workerId, workers[id]); else await societyAgencyAPI.addWorker(id, workers[id] || emptyWorker); toast.success(workerId ? 'Worker updated' : 'Worker added'); resetWorker(id); load() } catch (x) { toast.error(x.response?.data?.message || 'Unable to save worker') } }
  const removeAgency = async (id) => { if (!window.confirm('Deactivate this agency and its workers?')) return; try { await societyAgencyAPI.remove(id); if (editingAgencyId === id) resetAgency(); load() } catch (e) { toast.error(e.response?.data?.message || 'Unable to deactivate agency') } }
  const removeWorker = async (id, workerId) => { if (!window.confirm('Remove this agency worker?')) return; try { await societyAgencyAPI.removeWorker(id, workerId); if (editingWorkers[id] === workerId) resetWorker(id); load() } catch (e) { toast.error(e.response?.data?.message || 'Unable to remove worker') } }
  const agencyField = (label, key, props = {}) => <label>{label}<input {...props} value={agency[key]} onChange={(e) => setAgency({ ...agency, [key]: e.target.value })} /></label>

  return <Shell title="Agencies & Workers" eyebrow="Society workforce">
    <div className="agency-page">
    {canManage && <div className="agency-page-toolbar"><button className="primary" onClick={() => { resetAgency(); setAgencyOpen(true) }}>Add agency</button><select aria-label="Agency for new worker" value={selectedAgencyId} onChange={(e) => setSelectedAgencyId(e.target.value)}><option value="">Select agency</option>{rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!selectedAgencyId} onClick={() => { resetWorker(Number(selectedAgencyId)); setWorkerAgencyId(Number(selectedAgencyId)) }}>Add worker</button></div>}
    <SummaryGrid items={[["Active agencies", rows.length], ["Agency workers", rows.reduce((n, x) => n + (x.workers?.length || 0), 0)], ["Required headcount", rows.reduce((n, x) => n + Number(x.requiredHeadcount || 0), 0)]]} />
    <div className="agency-tabs" role="tablist" aria-label="Choose agency"><button role="tab" aria-selected={activeAgencyId === 'all'} onClick={() => setActiveAgencyId('all')}>All agencies <span>{rows.length}</span></button>{rows.map((item) => <button role="tab" key={item.id} aria-selected={String(activeAgencyId) === String(item.id)} onClick={() => setActiveAgencyId(item.id)}>{item.name} <span>{item.workers?.length || 0}</span></button>)}</div>
    {canManage && <form className="form-panel" onSubmit={saveAgency}><h2>{editingAgencyId ? 'Edit agency' : 'Add agency'}</h2><div className="form-grid">{agencyField('Name', 'name', { required: true })}{agencyField('Service category', 'serviceCategory', { required: true, placeholder: 'Security, cleaning...' })}{agencyField('Contact person', 'contactPerson')}{agencyField('Phone', 'phone')}{agencyField('Email', 'email', { type: 'email' })}{agencyField('Required headcount', 'requiredHeadcount', { type: 'number', min: 0 })}{agencyField('Contract start', 'contractStart', { type: 'date' })}{agencyField('Contract end', 'contractEnd', { type: 'date' })}</div><div className="form-actions">{editingAgencyId && <button type="button" onClick={resetAgency}>Cancel</button>}<button className="primary" disabled={busy}>{busy ? 'Saving...' : editingAgencyId ? 'Save agency changes' : 'Add agency'}</button></div></form>}
    {rows.map((item) => { const form = workers[item.id] || emptyWorker, editingId = editingWorkers[item.id]; return <section className="report-panel" key={item.id}><div className="section-heading-row"><div><h2>{item.name}</h2><p className="muted">{item.serviceCategory} · Required: {item.requiredHeadcount} · {item.contactPerson || 'No contact'} {item.phone || ''}</p></div>{canManage && <div className="table-actions"><button onClick={() => editAgency(item)}>Edit agency</button><button className="danger" onClick={() => removeAgency(item.id)}>Deactivate</button></div>}</div><div className="table-wrap"><table><thead><tr><th>Worker</th><th>Code</th><th>Designation</th><th>Mobile</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{item.workers?.map((w) => <tr key={w.id}><td>{w.workerName}</td><td>{w.workerCode || '-'}</td><td>{w.designation || '-'}</td><td>{w.mobile || '-'}</td>{canManage && <td className="table-actions"><button onClick={() => editWorker(item.id, w)}>Edit</button><button className="danger" onClick={() => removeWorker(item.id, w.id)}>Remove</button></td>}</tr>)}{!item.workers?.length && <tr><td className="empty-state" colSpan={canManage ? 5 : 4}>No workers added.</td></tr>}</tbody></table></div>{canManage && <form className="form-grid" onSubmit={(e) => saveWorker(e, item.id)}>{[['Worker name','workerName'],['Worker code','workerCode'],['Designation','designation'],['Mobile','mobile']].map(([label,key]) => <label key={key}>{label}<input required={key === 'workerName'} value={form[key]} onChange={(e) => setWorker(item.id, key, e.target.value)} /></label>)}<div className="form-actions">{editingId && <button type="button" onClick={() => resetWorker(item.id)}>Cancel</button>}<button className="primary">{editingId ? 'Save worker changes' : 'Add worker'}</button></div></form>}</section> })}
    {!rows.length && <p className="empty-state">No agencies configured.</p>}
    {agencyOpen && <dialog open className="agency-modal"><form onSubmit={saveAgency}><header><h2>{editingAgencyId ? 'Edit agency' : 'Add agency'}</h2><button type="button" aria-label="Close" onClick={resetAgency}>×</button></header><div className="form-grid">{agencyField('Name', 'name', { required: true })}{agencyField('Service category', 'serviceCategory', { required: true })}{agencyField('Contact person', 'contactPerson')}{agencyField('Phone', 'phone')}{agencyField('Email', 'email', { type: 'email' })}{agencyField('Required headcount', 'requiredHeadcount', { type: 'number', min: 0 })}{agencyField('Contract start', 'contractStart', { type: 'date' })}{agencyField('Contract end', 'contractEnd', { type: 'date' })}</div><footer><button type="button" onClick={resetAgency}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save agency'}</button></footer></form></dialog>}
    {workerAgencyId && (() => { const form = workers[workerAgencyId] || emptyWorker; return <dialog open className="agency-modal"><form onSubmit={(e) => saveWorker(e, workerAgencyId)}><header><h2>{editingWorkers[workerAgencyId] ? 'Edit worker' : 'Add worker'}</h2><button type="button" aria-label="Close" onClick={() => resetWorker(workerAgencyId)}>×</button></header><div className="form-grid">{[['Worker name','workerName'],['Worker code','workerCode'],['Designation','designation'],['Mobile','mobile']].map(([label,key]) => <label key={key}>{label}<input required={key === 'workerName'} value={form[key]} onChange={(e) => setWorker(workerAgencyId, key, e.target.value)} /></label>)}</div><footer><button type="button" onClick={() => resetWorker(workerAgencyId)}>Cancel</button><button className="primary">Save worker</button></footer></form></dialog> })()}
    </div>
  </Shell>
}
