import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { societyAgencyAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'

const emptyAgency = { name: '', serviceCategory: '', contactPerson: '', phone: '', email: '', contractStart: '', contractEnd: '', requiredHeadcount: 0 }
const emptyWorker = { workerName: '', workerCode: '', designation: '', mobile: '' }

export const AgencyList = () => {
  const role = useAuthStore((state) => state.currentAccount?.role); const canManage = role === 'ADMIN'
  const [rows, setRows] = useState([]); const [agency, setAgency] = useState(emptyAgency); const [workerByAgency, setWorkerByAgency] = useState({}); const [busy, setBusy] = useState(false)
  const load = () => societyAgencyAPI.list().then(({ data }) => setRows(data || [])).catch((e) => toast.error(e.response?.data?.message || 'Unable to load agencies'))
  useEffect(() => { load() }, [])
  const createAgency = async (e) => { e.preventDefault(); setBusy(true); try { await societyAgencyAPI.create({ ...agency, contractStart: agency.contractStart || null, contractEnd: agency.contractEnd || null, requiredHeadcount: Number(agency.requiredHeadcount || 0) }); setAgency(emptyAgency); toast.success('Agency added'); load() } catch (x) { toast.error(x.response?.data?.message || 'Unable to add agency') } finally { setBusy(false) } }
  const addWorker = async (e, id) => { e.preventDefault(); const form = workerByAgency[id] || emptyWorker; try { await societyAgencyAPI.addWorker(id, form); setWorkerByAgency((v) => ({ ...v, [id]: emptyWorker })); toast.success('Worker added'); load() } catch (x) { toast.error(x.response?.data?.message || 'Unable to add worker') } }
  const removeAgency = async (id) => { if (!window.confirm('Deactivate this agency and its workers?')) return; await societyAgencyAPI.remove(id); load() }
  const removeWorker = async (id, workerId) => { if (!window.confirm('Remove this agency worker?')) return; await societyAgencyAPI.removeWorker(id, workerId); load() }
  const setWorker = (id, key, value) => setWorkerByAgency((v) => ({ ...v, [id]: { ...(v[id] || emptyWorker), [key]: value } }))
  return <Shell title="Agencies & Workers" eyebrow="Society workforce">
    <SummaryGrid items={[["Active agencies", rows.length], ["Agency workers", rows.reduce((n, x) => n + (x.workers?.length || 0), 0)], ["Required headcount", rows.reduce((n, x) => n + Number(x.requiredHeadcount || 0), 0)]]} />
    {canManage && <form className="form-panel" onSubmit={createAgency}><h2>Add agency</h2><div className="form-grid"><label>Name<input required value={agency.name} onChange={(e) => setAgency({ ...agency, name: e.target.value })} /></label><label>Service category<input required placeholder="Security, cleaning..." value={agency.serviceCategory} onChange={(e) => setAgency({ ...agency, serviceCategory: e.target.value })} /></label><label>Contact person<input value={agency.contactPerson} onChange={(e) => setAgency({ ...agency, contactPerson: e.target.value })} /></label><label>Phone<input value={agency.phone} onChange={(e) => setAgency({ ...agency, phone: e.target.value })} /></label><label>Email<input type="email" value={agency.email} onChange={(e) => setAgency({ ...agency, email: e.target.value })} /></label><label>Required headcount<input type="number" min="0" value={agency.requiredHeadcount} onChange={(e) => setAgency({ ...agency, requiredHeadcount: e.target.value })} /></label><label>Contract start<input type="date" value={agency.contractStart} onChange={(e) => setAgency({ ...agency, contractStart: e.target.value })} /></label><label>Contract end<input type="date" value={agency.contractEnd} onChange={(e) => setAgency({ ...agency, contractEnd: e.target.value })} /></label></div><button className="primary" disabled={busy}>Add agency</button></form>}
    {rows.map((item) => <section className="report-panel" key={item.id}><div className="section-heading-row"><div><h2>{item.name}</h2><p className="muted">{item.serviceCategory} · Required: {item.requiredHeadcount} · {item.contactPerson || 'No contact'} {item.phone || ''}</p></div>{canManage && <button className="danger" onClick={() => removeAgency(item.id)}>Deactivate</button>}</div><div className="table-wrap"><table><thead><tr><th>Worker</th><th>Code</th><th>Designation</th><th>Mobile</th>{canManage && <th>Action</th>}</tr></thead><tbody>{item.workers?.map((w) => <tr key={w.id}><td>{w.workerName}</td><td>{w.workerCode || '-'}</td><td>{w.designation || '-'}</td><td>{w.mobile || '-'}</td>{canManage && <td><button className="danger" onClick={() => removeWorker(item.id, w.id)}>Remove</button></td>}</tr>)}{!item.workers?.length && <tr><td className="empty-state" colSpan={canManage ? 5 : 4}>No workers added.</td></tr>}</tbody></table></div>{canManage && <form className="form-grid" onSubmit={(e) => addWorker(e, item.id)}><label>Worker name<input required value={(workerByAgency[item.id] || emptyWorker).workerName} onChange={(e) => setWorker(item.id, 'workerName', e.target.value)} /></label><label>Worker code<input value={(workerByAgency[item.id] || emptyWorker).workerCode} onChange={(e) => setWorker(item.id, 'workerCode', e.target.value)} /></label><label>Designation<input value={(workerByAgency[item.id] || emptyWorker).designation} onChange={(e) => setWorker(item.id, 'designation', e.target.value)} /></label><label>Mobile<input value={(workerByAgency[item.id] || emptyWorker).mobile} onChange={(e) => setWorker(item.id, 'mobile', e.target.value)} /></label><button className="primary">Add worker</button></form>}</section>)}
    {!rows.length && <p className="empty-state">No agencies configured.</p>}
  </Shell>
}
