import { useEffect, useMemo, useState } from 'react'
import { toast } from 'react-toastify'
import { societyAgencyAPI, societyAttendanceAPI, societyAttendanceWorkflowAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'
const today=new Date().toISOString().slice(0,10),statuses=['PRESENT','ABSENT','LATE','HALF_DAY','ON_LEAVE','WEEKLY_OFF','HOLIDAY','NOT_SCHEDULED']
export const Attendance=()=>{const isAdmin=useAuthStore(s=>s.currentAccount?.role==='ADMIN');const[date,setDate]=useState(today),[rows,setRows]=useState([]),[agencies,setAgencies]=useState([]),[shortages,setShortages]=useState([]),[sheet,setSheet]=useState({status:'DRAFT'}),[corrections,setCorrections]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const load=()=>{setLoading(true);Promise.all([societyAttendanceAPI.getDay(date),societyAgencyAPI.list(),societyAttendanceAPI.getShortages(date),societyAttendanceWorkflowAPI.status(date),isAdmin?societyAttendanceWorkflowAPI.pendingCorrections():Promise.resolve({data:[]})]).then(([r,a,s,h,c])=>{setRows(r.data||[]);setAgencies(a.data||[]);setShortages(s.data||[]);setSheet(h.data||{status:'DRAFT'});setCorrections(c.data||[])}).catch(e=>toast.error(e.response?.data?.message||'Unable to load attendance')).finally(()=>setLoading(false))};useEffect(()=>{load()},[date,isAdmin])
 const update=(id,key,value)=>setRows(v=>v.map(x=>x.rosterAssignmentId===id?{...x,[key]:value}:x)),replacements=row=>(agencies.find(a=>a.id===row.agencyId)?.workers||[]).filter(w=>w.workerName!==row.assigneeName)
 const save=async()=>{setSaving(true);try{const entries=rows.map(x=>({rosterAssignmentId:x.rosterAssignmentId,status:x.status,checkIn:x.checkIn||null,checkOut:x.checkOut||null,replacementAgencyWorkerId:x.replacementAgencyWorkerId?Number(x.replacementAgencyWorkerId):null,notes:x.notes||null}));const r=await societyAttendanceAPI.saveBulk(date,entries);setRows(r.data||[]);toast.success('Attendance saved')}catch(e){toast.error(e.response?.data?.message||'Unable to save')}finally{setSaving(false)}}
 const submit=async()=>{try{setSheet((await societyAttendanceWorkflowAPI.submit(date)).data);toast.success('Attendance submitted')}catch(e){toast.error(e.response?.data?.message||'Unable to submit')}},lock=async()=>{try{setSheet((await societyAttendanceWorkflowAPI.lock(date)).data);toast.success('Sheet locked')}catch(e){toast.error(e.response?.data?.message||'Unable to lock')}}
 const correction=async r=>{const requestedStatus=window.prompt('Correct status:',r.status),reason=requestedStatus&&window.prompt('Reason for correction:');if(!reason)return;try{await societyAttendanceWorkflowAPI.requestCorrection(r.id,{requestedStatus:requestedStatus.toUpperCase(),requestedCheckIn:r.checkIn||null,requestedCheckOut:r.checkOut||null,reason});toast.success('Correction requested')}catch(e){toast.error(e.response?.data?.message||'Unable to request correction')}},approve=async id=>{await societyAttendanceWorkflowAPI.approveCorrection(id);toast.success('Correction approved');load()}
 const counts=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,rows.filter(x=>x.status===s).length])),[rows]),draft=sheet.status==='DRAFT'
 return <Shell title="Today's Attendance" eyebrow={`Attendance · ${sheet.status}`} actions={<div className="table-actions">{draft?<><button className="primary" disabled={saving||!rows.length} onClick={save}>{saving?'Saving...':'Save'}</button><button disabled={!rows.some(x=>x.id)} onClick={submit}>Submit</button></>:isAdmin&&sheet.status==='SUBMITTED'?<button className="primary" onClick={lock}>Lock sheet</button>:<strong>{sheet.status}</strong>}</div>}><SummaryGrid items={[["Expected",rows.length],["Present",counts.PRESENT||0],["Absent",counts.ABSENT||0],["Shortage",shortages.reduce((n,x)=>n+Number(x.shortage||0),0)]]}/>
 {isAdmin&&corrections.length>0&&<section className="report-panel"><h2>Pending corrections</h2>{corrections.map(c=><div className="toolbar-panel" key={c.id}><span><strong>{c.workerName}</strong> · {c.originalStatus} → {c.requestedStatus}<br/><small>{c.reason}</small></span><button onClick={()=>approve(c.id)}>Approve</button></div>)}</section>}
 {shortages.length>0&&<section className="report-panel"><h2>Agency staffing</h2>{shortages.map(x=><p key={x.agencyId}>{x.agencyName}: required {x.required}, present {x.present}, replacements {x.replacements}, <strong>shortage {x.shortage}</strong></p>)}</section>}
 <section className="toolbar-panel"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/>{draft&&<div className="table-actions"><button onClick={()=>setRows(v=>v.map(x=>({...x,status:'PRESENT'})))}>All present</button><button onClick={()=>setRows(v=>v.map(x=>({...x,status:'ABSENT'})))}>All absent</button></div>}</section>
 <div className="table-wrap"><table><thead><tr><th>Person</th><th>Agency</th><th>Shift / Post</th><th>Status</th><th>Replacement</th><th>In</th><th>Out</th><th>Notes</th>{!draft&&<th>Correction</th>}</tr></thead><tbody>{rows.map(x=><tr key={x.rosterAssignmentId}><td>{x.assigneeName}</td><td>{x.agencyName||'Direct'}</td><td>{x.shiftName}<br/><small>{x.postName}</small></td><td><select disabled={!draft} value={x.status} onChange={e=>update(x.rosterAssignmentId,'status',e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{draft&&x.agencyId&&x.status==='ABSENT'?<select value={x.replacementAgencyWorkerId||''} onChange={e=>update(x.rosterAssignmentId,'replacementAgencyWorkerId',e.target.value)}><option value="">None</option>{replacements(x).map(w=><option key={w.id} value={w.id}>{w.workerName}</option>)}</select>:x.replacementWorkerName||'-'}</td><td><input disabled={!draft} type="time" value={x.checkIn||''} onChange={e=>update(x.rosterAssignmentId,'checkIn',e.target.value)}/></td><td><input disabled={!draft} type="time" value={x.checkOut||''} onChange={e=>update(x.rosterAssignmentId,'checkOut',e.target.value)}/></td><td><input disabled={!draft} value={x.notes||''} onChange={e=>update(x.rosterAssignmentId,'notes',e.target.value)}/></td>{!draft&&<td><button disabled={!x.id} onClick={()=>correction(x)}>Request</button></td>}</tr>)}{!loading&&!rows.length&&<tr><td colSpan="9" className="empty-state">No roster assignments.</td></tr>}</tbody></table></div>{loading&&<p>Loading...</p>}</Shell>}
