import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { Link } from 'react-router-dom'
import { societyComplaintAPI, societyFlatAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'
const empty={flatId:'',title:'',description:'',category:'OTHER',priority:'NORMAL'}
export const Complaints=()=>{const role=useAuthStore(s=>s.currentAccount?.role),operations=['ADMIN','SUPERVISOR','TREASURER','STAFF_SUPERVISOR'].includes(role);const[rows,setRows]=useState([]),[flats,setFlats]=useState([]),[form,setForm]=useState(empty),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([societyComplaintAPI.list(),societyFlatAPI.getFlats()]).then(([c,f])=>{setRows(c.data||[]);setFlats(f.data||[])}).catch(e=>toast.error(e.response?.data?.message||'Unable to load complaints'));useEffect(()=>{load()},[])
 const open=async id=>{try{setSelected((await societyComplaintAPI.get(id)).data)}catch(e){toast.error(e.response?.data?.message||'Unable to open complaint')}}
 const create=async e=>{e.preventDefault();setBusy(true);try{await societyComplaintAPI.create({...form,flatId:Number(form.flatId)});setForm(empty);toast.success('Complaint raised');load()}catch(e){toast.error(e.response?.data?.message||'Unable to raise complaint')}finally{setBusy(false)}}
 const update=async()=>{const notes=window.prompt('Update notes:');if(!notes)return;let status=null,residentVisible=true;if(operations){status=window.prompt('Status: OPEN, ACKNOWLEDGED, IN_PROGRESS, RESOLVED, or CLOSED',selected.status);residentVisible=window.confirm('Should this update be visible to the resident?')}try{const{data}=await societyComplaintAPI.update(selected.id,{notes,status:status?.toUpperCase()||null,residentVisible});setSelected(data);load();toast.success('Complaint updated')}catch(e){toast.error(e.response?.data?.message||'Unable to update complaint')}}
 const convert=async()=>{if(!window.confirm('Create a work order from this complaint?'))return;try{const{data}=await societyComplaintAPI.convert(selected.id,{});setSelected(data);load();toast.success('Work order created')}catch(e){toast.error(e.response?.data?.message||'Unable to create work order')}}
 return <Shell title="Complaints" eyebrow="Society operations"><SummaryGrid items={[["Open",rows.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length],["High priority",rows.filter(x=>['HIGH','EMERGENCY'].includes(x.priority)&&!['RESOLVED','CLOSED'].includes(x.status)).length],["Resolved",rows.filter(x=>x.status==='RESOLVED').length],["Total",rows.length]]}/>
  <form className="form-panel" onSubmit={create}><h2>Raise complaint</h2><div className="form-grid"><label>Flat<select required value={form.flatId} onChange={e=>setForm({...form,flatId:e.target.value})}><option value="">Select flat</option>{flats.map(x=><option key={x.id} value={x.id}>{x.blockName} / {x.flatNumber}</option>)}</select></label><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['ELECTRICAL','PLUMBING','LIFT','CLEANING','SECURITY','CIVIL','GARDENING','FIRE_SAFETY','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','NORMAL','HIGH','EMERGENCY'].map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="primary" disabled={busy}>Submit complaint</button></form>
  <div className="table-wrap"><table><thead><tr><th>Complaint</th><th>Flat</th><th>Resident</th><th>Priority</th><th>Status</th><th>Work order</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.complaintNumber}</strong><br/><small>{x.title}</small></td><td>{x.flat}</td><td>{x.complainantName}</td><td>{x.priority}</td><td><span className={`status-pill ${x.status==='RESOLVED'?'approved':x.priority==='EMERGENCY'?'rejected':''}`}>{x.status}</span></td><td>{x.workOrderNumber?<Link to="/society/work-orders">{x.workOrderNumber}</Link>:'-'}</td><td><button onClick={()=>open(x.id)}>Open</button></td></tr>)}</tbody></table></div>
  {selected&&<section className="report-panel"><div className="section-heading-row"><div><h2>{selected.complaintNumber} · {selected.title}</h2><p>{selected.description}</p><p className="muted">{selected.flat} · {selected.complainantName} · {selected.status}</p></div><button onClick={()=>setSelected(null)}>Close</button></div><div className="form-actions">{selected.status!=='CLOSED'&&<button onClick={update}>Add update</button>}{operations&&!selected.workOrderId&&!['RESOLVED','CLOSED'].includes(selected.status)&&<button className="primary" onClick={convert}>Create work order</button>}{selected.workOrderId&&<Link className="button-link" to="/society/work-orders">Open {selected.workOrderNumber}</Link>}</div><h3>Timeline</h3>{selected.updates?.map(x=><p key={x.id}><strong>{x.status}</strong> · {x.createdBy} · {new Date(x.createdAt).toLocaleString()}{operations&&!x.residentVisible?' · Internal':''}<br/><span className="muted">{x.notes}</span></p>)}</section>}
 </Shell>}
