import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { societyDailyOperationsAPI as api } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'

const today = new Date().toISOString().slice(0, 10)
const nowLocal = () => { const d = new Date(); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16) }
const blankIncident = () => ({ title: '', description: '', severity: 'MEDIUM', location: '', occurredAt: nowLocal(), immediateAction: '', sensitive: false })
const blankInspection = () => ({ title: '', location: '', scheduledFor: nowLocal(), checklist: '' })
const blankHandover = () => ({ shiftDate: today, shiftName: '', openItems: '', incidents: '', expectedVisitors: '', assetsHandedOver: '', equipmentStatus: '', attendanceShortages: '', notes: '', receiverName: '' })

export const DailyOperations = () => {
  const { currentAccount } = useAuthStore(), admin = currentAccount?.role === 'ADMIN'
  const [date, setDate] = useState(today), [tab, setTab] = useState('checklist'), [dashboard, setDashboard] = useState(null)
  const [checklist, setChecklist] = useState([]), [incidents, setIncidents] = useState([]), [inspections, setInspections] = useState([]), [handovers, setHandovers] = useState([]), [reports, setReports] = useState([])
  const [incident, setIncident] = useState(blankIncident()), [inspection, setInspection] = useState(blankInspection()), [handover, setHandover] = useState(blankHandover()), [report, setReport] = useState({ summary: '', nextDayPriorities: '' })
  const load = async () => { try { const [d,c,i,n,h,r] = await Promise.all([api.dashboard(date),api.checklist(date),api.incidents(),api.inspections(),api.handovers(),api.reports()]); setDashboard(d.data);setChecklist(c.data||[]);setIncidents(i.data||[]);setInspections(n.data||[]);setHandovers(h.data||[]);setReports(r.data||[]) } catch(e){ toast.error(e.response?.data?.message || 'Unable to load daily operations') } }
  useEffect(() => { load() }, [date])
  const run = async (action, success) => { try { await action(); toast.success(success); await load() } catch(e){ toast.error(e.response?.data?.message || 'Unable to save') } }
  const addChecklist = () => { const title = window.prompt('Checklist item'); if(title?.trim()) run(() => api.createChecklistTemplate({ title: title.trim(), sortOrder: checklist.length }), 'Checklist item added') }
  const updateChecklist = (item, completed) => run(() => api.updateChecklist(item.templateId,date,{completed,notes:item.notes||''}), completed?'Checklist item completed':'Checklist item reopened')
  const submitIncident = e => { e.preventDefault(); run(() => api.createIncident(incident), 'Incident recorded').then(() => setIncident(blankIncident())) }
  const closeIncident = item => { const followUp=window.prompt('Closure/follow-up notes'); if(followUp!==null) run(() => api.updateIncident(item.id,{status:'CLOSED',followUp}), 'Incident closed') }
  const submitInspection = e => { e.preventDefault(); run(() => api.createInspection(inspection), 'Inspection scheduled').then(() => setInspection(blankInspection())) }
  const completeInspection = item => { const result=window.prompt('Result: PASS, FAIL, or NOT_APPLICABLE','PASS')?.toUpperCase(); if(!result)return; const notes=window.prompt('Inspection notes','')||''; const failureAction=result==='FAIL'?(window.prompt('Required failure action')||''):''; run(() => api.completeInspection(item.id,{result,notes,failureAction}), 'Inspection completed') }
  const submitHandover = e => { e.preventDefault(); run(() => api.createHandover(handover), 'Handover recorded').then(() => setHandover(blankHandover())) }
  const saveReport = submit => run(() => submit ? api.submitReport({reportDate:date,...report}) : api.saveReport({reportDate:date,...report}), submit?'Daily report submitted':'Draft saved')
  const acknowledgeReport = item => { const comment=window.prompt('Admin acknowledgement comment',''); if(comment!==null) run(() => api.acknowledgeReport(item.id,comment), 'Report acknowledged') }
  const field = setter => e => setter(v => ({...v,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}))
  const tabs = [['checklist','Checklist'],['incidents','Incidents'],['inspections','Inspections'],['handover','Handover'],['report','Daily Report']]
  return <Shell title="Daily Operations" eyebrow="Society operations" actions={<label>Operating date <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}>
    <SummaryGrid items={[["Checklist",`${dashboard?.checklistCompleted||0}/${dashboard?.checklistTotal||0}`],["Present",dashboard?.present||0],["Open work",dashboard?.openWorkOrders||0],["Overdue",dashboard?.overdueWorkOrders||0],["Complaints",dashboard?.openComplaints||0],["Incidents",dashboard?.openIncidents||0],["Inspections due",dashboard?.inspectionsDue||0],["Report",dashboard?.reportStatus||'NOT_STARTED']]} />
    <div className="table-actions">{tabs.map(([id,label])=><button key={id} className={tab===id?'primary':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='checklist'&&<section className="report-panel"><div className="section-heading-row"><div><h2>Daily checklist</h2><p className="muted">Completion is recorded with the operator and time.</p></div>{admin&&<button onClick={addChecklist}>Add checklist item</button>}</div>{checklist.map(x=><article className="shared-invitation-card" key={x.templateId}><label><input type="checkbox" checked={x.completed} onChange={e=>updateChecklist(x,e.target.checked)}/> <strong>{x.title}</strong></label><span className="muted">{x.description||''}{x.completedBy?` · ${x.completedBy} · ${new Date(x.completedAt).toLocaleString()}`:''}</span>{admin&&<button className="danger" onClick={()=>run(()=>api.disableChecklistTemplate(x.templateId),'Checklist item removed')}>Remove</button>}</article>)}{!checklist.length&&<p className="empty-state">No checklist items configured. An admin can add the first one.</p>}</section>}
    {tab==='incidents'&&<><form className="form-panel" onSubmit={submitIncident}><h2>Record incident</h2><div className="form-grid"><label>Title<input name="title" value={incident.title} onChange={field(setIncident)} required/></label><label>Severity<select name="severity" value={incident.severity} onChange={field(setIncident)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Occurred at<input type="datetime-local" name="occurredAt" value={incident.occurredAt} onChange={field(setIncident)} required/></label><label>Location<input name="location" value={incident.location} onChange={field(setIncident)}/></label><label className="full-width">Description<textarea name="description" value={incident.description} onChange={field(setIncident)} required/></label><label className="full-width">Immediate action<textarea name="immediateAction" value={incident.immediateAction} onChange={field(setIncident)}/></label><label><input type="checkbox" name="sensitive" checked={incident.sensitive} onChange={field(setIncident)}/> Restricted/sensitive</label></div><button className="primary">Record incident</button></form><section className="report-panel">{incidents.map(x=><article className="shared-invitation-card" key={x.id}><div><strong>{x.incidentNumber} · {x.title}</strong><p>{x.description}</p><small>{x.severity} · {x.status} · {new Date(x.occurredAt).toLocaleString()} · {x.location||'No location'}</small></div>{x.status!=='CLOSED'&&<button onClick={()=>closeIncident(x)}>Close</button>}</article>)}</section></>}
    {tab==='inspections'&&<><form className="form-panel" onSubmit={submitInspection}><h2>Schedule inspection</h2><div className="form-grid"><label>Title<input name="title" value={inspection.title} onChange={field(setInspection)} required/></label><label>Location<input name="location" value={inspection.location} onChange={field(setInspection)}/></label><label>Scheduled for<input type="datetime-local" name="scheduledFor" value={inspection.scheduledFor} onChange={field(setInspection)}/></label><label className="full-width">Checklist<textarea name="checklist" value={inspection.checklist} onChange={field(setInspection)} placeholder="One inspection point per line"/></label></div><button className="primary">Schedule</button></form><section className="report-panel">{inspections.map(x=><article className="shared-invitation-card" key={x.id}><div><strong>{x.title}</strong><p>{x.checklist}</p><small>{x.result} · {x.scheduledFor?new Date(x.scheduledFor).toLocaleString():'Ad-hoc'} · {x.location||'No location'}</small>{x.failureAction&&<p>Failure action: {x.failureAction}</p>}</div>{x.result==='PENDING'&&<button onClick={()=>completeInspection(x)}>Complete</button>}</article>)}</section></>}
    {tab==='handover'&&<><form className="form-panel" onSubmit={submitHandover}><h2>Shift handover</h2><div className="form-grid"><label>Date<input type="date" name="shiftDate" value={handover.shiftDate} onChange={field(setHandover)} required/></label><label>Shift<input name="shiftName" value={handover.shiftName} onChange={field(setHandover)} required/></label>{[['openItems','Open work and complaints'],['incidents','Incidents'],['expectedVisitors','Expected visitors/vendors'],['assetsHandedOver','Keys, devices, documents'],['equipmentStatus','Equipment status'],['attendanceShortages','Attendance shortages'],['notes','Notes for next shift']].map(([name,label])=><label key={name}>{label}<textarea name={name} value={handover[name]} onChange={field(setHandover)}/></label>)}<label>Receiver name<input name="receiverName" value={handover.receiverName} onChange={field(setHandover)}/></label></div><button className="primary">Record handover</button></form><section className="report-panel">{handovers.map(x=><article className="shared-invitation-card" key={x.id}><div><strong>{x.shiftDate} · {x.shiftName}</strong><p>{x.openItems||x.notes||'No open notes'}</p><small>Sent by {x.sender}{x.acknowledgedBy?` · Acknowledged by ${x.acknowledgedBy}`:''}</small></div>{!x.acknowledgedAt&&<button onClick={()=>run(()=>api.acknowledgeHandover(x.id),'Handover acknowledged')}>Acknowledge</button>}</article>)}</section></>}
    {tab==='report'&&<><section className="form-panel"><h2>Supervisor daily report</h2><p className="muted">Attendance, work, complaints, incidents, inspections, handovers, and checklist totals are captured automatically when saved.</p><label>Summary<textarea value={report.summary} onChange={e=>setReport({...report,summary:e.target.value})}/></label><label>Next-day priorities<textarea value={report.nextDayPriorities} onChange={e=>setReport({...report,nextDayPriorities:e.target.value})}/></label><div className="form-actions"><button onClick={()=>saveReport(false)}>Save draft</button><button className="primary" onClick={()=>saveReport(true)}>Submit report</button></div></section><section className="report-panel"><h2>Report history</h2>{reports.map(x=><article className="shared-invitation-card" key={x.id}><div><strong>{x.reportDate} · Revision {x.revision} · {x.status}</strong><p>{x.summary||'No supervisor summary'}</p><small>{Object.entries(x.snapshot||{}).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join(' · ')}</small>{x.adminComment&&<p>Admin: {x.adminComment}</p>}</div>{admin&&x.status==='SUBMITTED'&&<button className="primary" onClick={()=>acknowledgeReport(x)}>Acknowledge</button>}</article>)}</section></>}
  </Shell>
}
