import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'react-toastify'
import { societyStaffAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { formatCurrency, formatDate } from '../../utils/format'
import { Shell, SummaryGrid } from '../DashboardRouter'
import { useI18n } from '../../i18n'

export const StaffList = () => {
  const { tx } = useI18n()
  const navigate = useNavigate(); const { currentAccount } = useAuthStore(); const [staff, setStaff] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [accessByStaff, setAccessByStaff] = useState({}); const [invitationByStaff, setInvitationByStaff] = useState({}); const [accessBusy, setAccessBusy] = useState(null)
  const canWrite = currentAccount?.role !== 'MEMBER' && currentAccount?.role !== 'STAFF_SUPERVISOR'
  const canManageAccess = currentAccount?.role === 'ADMIN'
  const load = () => { if (currentAccount?.accountType !== 'SOCIETY') return setLoading(false); setLoading(true); societyStaffAPI.getStaff().then(async ({ data }) => { const rows = Array.isArray(data) ? data : []; setStaff(rows); if (canManageAccess) { const entries = await Promise.all(rows.map(async (item) => { try { const response = await societyStaffAPI.getAccess(item.id); return [item.id, response.data || null] } catch { return [item.id, null] } })); const invitations = await Promise.all(rows.map(async (item) => { try { const response = await societyStaffAPI.getLatestInvitation(item.id); return [item.id, response.data || null] } catch { return [item.id, null] } })); setAccessByStaff(Object.fromEntries(entries)); setInvitationByStaff(Object.fromEntries(invitations)) } }).catch((e) => toast.error(e.response?.data?.message || 'Unable to load staff')).finally(() => setLoading(false)) }
  useEffect(load, [currentAccount?.accountType])
  const visible = useMemo(() => { const q = search.trim().toLowerCase(); return staff.filter((s) => !q || [s.staffName, s.designation, s.mobile].filter(Boolean).some((v) => String(v).toLowerCase().includes(q))) }, [staff, search])
  const remove = async (id) => { if (!window.confirm(tx('Remove this staff member?'))) return; try { await societyStaffAPI.deleteStaff(id); toast.success(tx('Staff member removed')); load() } catch (e) { toast.error(e.response?.data?.message || tx('Delete failed')) } }
  const grantAccess = async (item) => { const accessRole = window.confirm(tx('Grant limited worker self-service only? Select Cancel for supervisor access.')) ? 'STAFF' : 'STAFF_SUPERVISOR'; setAccessBusy(item.id); try { const { data } = await societyStaffAPI.grantAccess(item.id, { accessRole }); setAccessByStaff((value) => ({ ...value, [item.id]: data })); toast.success(tx(accessRole === 'STAFF' ? 'Worker self-service access activated' : 'Supervisor workspace access activated')) } catch (e) { toast.error(e.response?.data?.message || tx('Unable to grant staff access')) } finally { setAccessBusy(null) } }
  const invite = async (item) => { setAccessBusy(item.id); try { const { data } = await societyStaffAPI.sendInvitation(item.id); setInvitationByStaff((value) => ({ ...value, [item.id]: data })); const link = `${window.location.origin}/staff-invitation?code=${encodeURIComponent(data.invitationCode)}`; await navigator.clipboard?.writeText(link); toast.success(tx('Invitation created and link copied. It expires in 7 days.')); window.prompt(tx('Share this invitation link with the staff member:'), link) } catch (e) { toast.error(e.response?.data?.message || tx('Unable to create invitation')) } finally { setAccessBusy(null) } }
  const changeAccess = async (item, status) => { setAccessBusy(item.id); try { const { data } = await societyStaffAPI.updateAccessStatus(item.id, status); setAccessByStaff((value) => ({ ...value, [item.id]: data })); toast.success(`${tx('Staff access')} ${tx(status)}`) } catch (e) { toast.error(e.response?.data?.message || tx('Unable to update staff access')) } finally { setAccessBusy(null) } }
  if (currentAccount?.accountType !== 'SOCIETY') return <Shell title="Staff" eyebrow="Society module"><p className="muted">{tx('Staff are available for society accounts.')}</p></Shell>
  return <Shell title="Society Staff" eyebrow="Society module" actions={canWrite && <Link className="button-link" to="/society/staff/new">{tx('Add Staff')}</Link>}>
    <SummaryGrid items={[[tx('Active Staff'), staff.length], [tx('Monthly Payroll'), formatCurrency(staff.reduce((sum, s) => sum + Number(s.monthlySalary || 0), 0))], [tx('Shown'), visible.length]]} />
    <section className="toolbar-panel"><input placeholder={tx('Search name, designation, mobile')} value={search} onChange={(e) => setSearch(e.target.value)} /><strong>{visible.length} {tx('shown')}</strong></section>
    <div className="table-wrap"><table><thead><tr><th>{tx('Name')}</th><th>{tx('Designation')}</th><th>{tx('Mobile')}</th><th>{tx('Joining Date')}</th><th className="numeric">{tx('Monthly Salary')}</th>{canManageAccess && <th>{tx('Workspace access')}</th>}<th>{tx('Actions')}</th></tr></thead><tbody>
      {visible.map((s) => { const access = accessByStaff[s.id]; const invitation = invitationByStaff[s.id]; const busy = accessBusy === s.id; const pending = invitation?.status === 'PENDING' && new Date(invitation.expiresAt) > new Date(); return <tr key={s.id}><td>{s.staffName}</td><td>{s.designation}</td><td>{s.mobile || '-'}</td><td>{s.joiningDate ? formatDate(s.joiningDate) : '-'}</td><td className="numeric">{formatCurrency(s.monthlySalary)}</td>{canManageAccess && <td><span className={`status-pill ${access?.status === 'ACTIVE' ? 'approved' : 'rejected'}`}>{tx(access?.status || (pending ? 'INVITED' : 'NOT GRANTED'))}</span><div className="table-actions">{!access || access.status === 'REVOKED' ? <><button disabled={busy} onClick={() => invite(s)}>{tx(pending ? 'Resend invite' : 'Invite')}</button><button disabled={busy} onClick={() => grantAccess(s)}>{tx('Direct grant')}</button></> : access.status === 'ACTIVE' ? <><button disabled={busy} onClick={() => changeAccess(s, 'SUSPENDED')}>{tx('Suspend')}</button><button className="danger" disabled={busy} onClick={() => changeAccess(s, 'REVOKED')}>{tx('Revoke')}</button></> : <><button disabled={busy} onClick={() => changeAccess(s, 'ACTIVE')}>{tx('Reactivate')}</button><button className="danger" disabled={busy} onClick={() => changeAccess(s, 'REVOKED')}>{tx('Revoke')}</button></>}</div></td>}<td className="table-actions">{canWrite ? <><button onClick={() => navigate(`/society/staff/${s.id}/edit`)}>{tx('Edit')}</button><button className="danger" disabled={access?.status === 'ACTIVE'} onClick={() => remove(s.id)}>{tx('Remove')}</button></> : <span className="muted">{tx('View only')}</span>}</td></tr> })}
      {!loading && !visible.length && <tr><td colSpan={canManageAccess ? '7' : '6'} className="empty-state">{tx('No staff members found.')}</td></tr>}
    </tbody></table></div>{loading && <p className="muted">{tx('Loading staff...')}</p>}
  </Shell>
}
