import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'react-toastify'
import { societyStaffAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { formatCurrency, formatDate } from '../../utils/format'
import { Shell, SummaryGrid } from '../DashboardRouter'

export const StaffList = () => {
  const navigate = useNavigate(); const { currentAccount } = useAuthStore(); const [staff, setStaff] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [accessByStaff, setAccessByStaff] = useState({}); const [invitationByStaff, setInvitationByStaff] = useState({}); const [accessBusy, setAccessBusy] = useState(null)
  const canWrite = currentAccount?.role !== 'MEMBER'
  const canManageAccess = currentAccount?.role === 'ADMIN'
  const load = () => { if (currentAccount?.accountType !== 'SOCIETY') return setLoading(false); setLoading(true); societyStaffAPI.getStaff().then(async ({ data }) => { const rows = Array.isArray(data) ? data : []; setStaff(rows); if (canManageAccess) { const entries = await Promise.all(rows.map(async (item) => { try { const response = await societyStaffAPI.getAccess(item.id); return [item.id, response.data || null] } catch { return [item.id, null] } })); const invitations = await Promise.all(rows.map(async (item) => { try { const response = await societyStaffAPI.getLatestInvitation(item.id); return [item.id, response.data || null] } catch { return [item.id, null] } })); setAccessByStaff(Object.fromEntries(entries)); setInvitationByStaff(Object.fromEntries(invitations)) } }).catch((e) => toast.error(e.response?.data?.message || 'Unable to load staff')).finally(() => setLoading(false)) }
  useEffect(load, [currentAccount?.accountType])
  const visible = useMemo(() => { const q = search.trim().toLowerCase(); return staff.filter((s) => !q || [s.staffName, s.designation, s.mobile].filter(Boolean).some((v) => String(v).toLowerCase().includes(q))) }, [staff, search])
  const remove = async (id) => { if (!window.confirm('Remove this staff member?')) return; try { await societyStaffAPI.deleteStaff(id); toast.success('Staff member removed'); load() } catch (e) { toast.error(e.response?.data?.message || 'Delete failed') } }
  const grantAccess = async (item) => { setAccessBusy(item.id); try { const { data } = await societyStaffAPI.grantAccess(item.id); setAccessByStaff((value) => ({ ...value, [item.id]: data })); toast.success('Supervisor workspace access activated') } catch (e) { toast.error(e.response?.data?.message || 'Unable to grant access. Ensure the staff mobile or email belongs to a registered user.') } finally { setAccessBusy(null) } }
  const invite = async (item) => { setAccessBusy(item.id); try { const { data } = await societyStaffAPI.sendInvitation(item.id); setInvitationByStaff((value) => ({ ...value, [item.id]: data })); const link = `${window.location.origin}/staff-invitation?code=${encodeURIComponent(data.invitationCode)}`; await navigator.clipboard?.writeText(link); toast.success('Invitation created and link copied. It expires in 7 days.'); window.prompt('Share this invitation link with the staff member:', link) } catch (e) { toast.error(e.response?.data?.message || 'Unable to create invitation') } finally { setAccessBusy(null) } }
  const changeAccess = async (item, status) => { setAccessBusy(item.id); try { const { data } = await societyStaffAPI.updateAccessStatus(item.id, status); setAccessByStaff((value) => ({ ...value, [item.id]: data })); toast.success(`Staff access ${status.toLowerCase()}`) } catch (e) { toast.error(e.response?.data?.message || 'Unable to update staff access') } finally { setAccessBusy(null) } }
  if (currentAccount?.accountType !== 'SOCIETY') return <Shell title="Staff" eyebrow="Society module"><p className="muted">Staff are available for society accounts.</p></Shell>
  return <Shell title="Society Staff" eyebrow="Society module" actions={canWrite && <Link className="button-link" to="/society/staff/new">Add Staff</Link>}>
    <SummaryGrid items={[["Active Staff", staff.length], ["Monthly Payroll", formatCurrency(staff.reduce((sum, s) => sum + Number(s.monthlySalary || 0), 0))], ["Shown", visible.length]]} />
    <section className="toolbar-panel"><input placeholder="Search name, designation, mobile" value={search} onChange={(e) => setSearch(e.target.value)} /><strong>{visible.length} shown</strong></section>
    <div className="table-wrap"><table><thead><tr><th>Name</th><th>Designation</th><th>Mobile</th><th>Joining Date</th><th className="numeric">Monthly Salary</th>{canManageAccess && <th>Workspace access</th>}<th>Actions</th></tr></thead><tbody>
      {visible.map((s) => { const access = accessByStaff[s.id]; const invitation = invitationByStaff[s.id]; const busy = accessBusy === s.id; const pending = invitation?.status === 'PENDING' && new Date(invitation.expiresAt) > new Date(); return <tr key={s.id}><td>{s.staffName}</td><td>{s.designation}</td><td>{s.mobile || '-'}</td><td>{s.joiningDate ? formatDate(s.joiningDate) : '-'}</td><td className="numeric">{formatCurrency(s.monthlySalary)}</td>{canManageAccess && <td><span className={`status-pill ${access?.status === 'ACTIVE' ? 'approved' : 'rejected'}`}>{access?.status || (pending ? 'INVITED' : 'NOT GRANTED')}</span><div className="table-actions">{!access || access.status === 'REVOKED' ? <><button disabled={busy} onClick={() => invite(s)}>{pending ? 'Resend invite' : 'Invite'}</button><button disabled={busy} onClick={() => grantAccess(s)}>Direct grant</button></> : access.status === 'ACTIVE' ? <><button disabled={busy} onClick={() => changeAccess(s, 'SUSPENDED')}>Suspend</button><button className="danger" disabled={busy} onClick={() => changeAccess(s, 'REVOKED')}>Revoke</button></> : <><button disabled={busy} onClick={() => changeAccess(s, 'ACTIVE')}>Reactivate</button><button className="danger" disabled={busy} onClick={() => changeAccess(s, 'REVOKED')}>Revoke</button></>}</div></td>}<td className="table-actions">{canWrite ? <><button onClick={() => navigate(`/society/staff/${s.id}/edit`)}>Edit</button><button className="danger" disabled={access?.status === 'ACTIVE'} onClick={() => remove(s.id)}>Remove</button></> : <span className="muted">View only</span>}</td></tr> })}
      {!loading && !visible.length && <tr><td colSpan={canManageAccess ? '7' : '6'} className="empty-state">No staff members found.</td></tr>}
    </tbody></table></div>{loading && <p className="muted">Loading staff...</p>}
  </Shell>
}
