import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { societyAgencyAPI, societyStaffAPI, societyVendorAPI, societyWorkOrderAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'

const empty = { title: '', description: '', category: 'OTHER', source: 'SUPERVISOR', location: '', priority: 'NORMAL', plannedStart: '', dueAt: '', estimatedCost: '' }
export const WorkOrders = () => {
  const role = useAuthStore((s) => s.currentAccount?.role); const admin = role === 'ADMIN'
  const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(empty),[staff,setStaff]=useState([]),[agencies,setAgencies]=useState([]),[vendors,setVendors]=useState([]),[assignee,setAssignee]=useState(''),[busy,setBusy]=useState(false)
  const load=()=>Promise.all([societyWorkOrderAPI.list(),societyStaffAPI.getStaff(),societyAgencyAPI.list(),societyVendorAPI.getVendors()]).then(([w,s,a,v])=>{setRows(w.data||[]);setStaff(s.data||[]);setAgencies(a.data||[]);setVendors(v.data||[])}).catch(e=>toast.error(e.response?.data?.message||'Unable to load work orders'))
  useEffect(()=>{load()},[])
  const open=async id=>{try{setSelected((await societyWorkOrderAPI.get(id)).data)}catch(e){toast.error(e.response?.data?.message||'Unable to open work order')}}
  const create=async e=>{e.preventDefault();setBusy(true);try{await societyWorkOrderAPI.create({...form,plannedStart:form.plannedStart||null,dueAt:form.dueAt||null,estimatedCost:form.estimatedCost===''?null:Number(form.estimatedCost)});setForm(empty);toast.success('Work order created');load()}catch(x){toast.error(x.response?.data?.message||'Unable to create work order')}finally{setBusy(false)}}
  const act=async fn=>{try{const {data}=await fn();setSelected(data);load()}catch(e){toast.error(e.response?.data?.message||'Unable to update work order')}}
  const assign=()=>{if(!assignee)return;const [type,id]=assignee.split(':');act(()=>societyWorkOrderAPI.assign(selected.id,{staffId:type==='staff'?Number(id):null,agencyId:type==='agency'?Number(id):null,vendorId:type==='vendor'?Number(id):null}))}
  const progress=()=>{const notes=window.prompt('Progress notes:');if(!notes)return;const status=window.prompt('Status: IN_PROGRESS or BLOCKED','IN_PROGRESS');if(status)act(()=>societyWorkOrderAPI.update(selected.id,{notes,status:status.toUpperCase()}))}
  const complete=()=>{const completionNotes=window.prompt('Completion notes:');if(!completionNotes)return;const cost=window.prompt('Actual cost (optional):','');act(()=>societyWorkOrderAPI.complete(selected.id,{completionNotes,actualCost:cost?Number(cost):null}))}
  const review=verify=>{const notes=window.prompt(verify?'Verification notes (optional):':'Reason for reopening:','');act(()=>verify?societyWorkOrderAPI.verify(selected.id,{notes}):societyWorkOrderAPI.reopen(selected.id,{notes}))}
  const active=rows.filter(x=>!['VERIFIED','CANCELLED'].includes(x.status)), overdue=rows.filter(x=>x.overdue)
  return <Shell title="Work Orders" eyebrow="Society operations"><SummaryGrid items={[["Open work",active.length],["Overdue",overdue.length],["Completed",rows.filter(x=>x.status==='COMPLETED').length],["Verified",rows.filter(x=>x.status==='VERIFIED').length]]}/>
   <form className="form-panel" onSubmit={create}><h2>Create work order</h2><div className="form-grid"><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['ELECTRICAL','PLUMBING','LIFT','CLEANING','SECURITY','CIVIL','GARDENING','FIRE_SAFETY','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','NORMAL','HIGH','EMERGENCY'].map(x=><option key={x}>{x}</option>)}</select></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Planned start<input type="datetime-local" value={form.plannedStart} onChange={e=>setForm({...form,plannedStart:e.target.value})}/></label><label>Due at<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label>Estimated cost<input type="number" min="0" step="0.01" value={form.estimatedCost} onChange={e=>setForm({...form,estimatedCost:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="primary" disabled={busy}>Create work order</button></form>
   <div className="table-wrap"><table><thead><tr><th>Order</th><th>Work</th><th>Priority</th><th>Status</th><th>Assigned to</th><th>Due</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.workOrderNumber}</td><td><strong>{x.title}</strong><br/><small>{x.location||x.category}</small></td><td>{x.priority}</td><td><span className={`status-pill ${x.overdue?'rejected':x.status==='VERIFIED'?'approved':''}`}>{x.overdue?'OVERDUE':x.status}</span></td><td>{x.assignments?.map(a=>a.assigneeName).join(', ')||'-'}</td><td>{x.dueAt?new Date(x.dueAt).toLocaleString():'-'}</td><td><button onClick={()=>open(x.id)}>Open</button></td></tr>)}</tbody></table></div>
   {selected&&<section className="report-panel"><div className="section-heading-row"><div><h2>{selected.workOrderNumber} · {selected.title}</h2><p className="muted">{selected.description||'No description'} · {selected.status}</p></div><button onClick={()=>setSelected(null)}>Close</button></div>{!['VERIFIED','CANCELLED'].includes(selected.status)&&<div className="form-actions"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Assign to...</option><optgroup label="Staff">{staff.map(x=><option key={`s${x.id}`} value={`staff:${x.id}`}>{x.staffName}</option>)}</optgroup><optgroup label="Agencies">{agencies.map(x=><option key={`a${x.id}`} value={`agency:${x.id}`}>{x.name}</option>)}</optgroup><optgroup label="Vendors">{vendors.map(x=><option key={`v${x.id}`} value={`vendor:${x.id}`}>{x.supplierName}</option>)}</optgroup></select><button onClick={assign}>Assign</button><button onClick={progress}>Add progress</button><button className="primary" onClick={complete}>Complete</button></div>}{admin&&selected.status==='COMPLETED'&&<div className="form-actions"><button className="primary" onClick={()=>review(true)}>Verify</button><button onClick={()=>review(false)}>Reopen</button></div>}<h3>Timeline</h3>{selected.updates?.map(x=><p key={x.id}><strong>{x.updateType}</strong> · {x.createdBy} · {new Date(x.createdAt).toLocaleString()}<br/><span className="muted">{x.notes}</span></p>)}</section>}
  </Shell>
}
