import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { attachmentAPI, expenseCategoryAPI, societyAgencyAPI, societyStaffAPI, societyVendorAPI, societyWorkOrderAPI } from '../../api/endpoints'
import { useAuthStore } from '../../store/authStore'
import { Shell, SummaryGrid } from '../DashboardRouter'

const empty = { title: '', description: '', category: 'OTHER', source: 'SUPERVISOR', location: '', priority: 'NORMAL', plannedStart: '', dueAt: '', estimatedCost: '', recurrenceType: '', recurrenceInterval: 1, recurrenceEnd: '' }
export const WorkOrders = () => {
  const role = useAuthStore((s) => s.currentAccount?.role); const admin = role === 'ADMIN'
  const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(empty),[staff,setStaff]=useState([]),[agencies,setAgencies]=useState([]),[vendors,setVendors]=useState([]),[categories,setCategories]=useState([]),[assignee,setAssignee]=useState(''),[attachments,setAttachments]=useState([]),[expenseRequests,setExpenseRequests]=useState([]),[expense,setExpense]=useState({categoryId:'',amount:'',description:'',vendorName:''}),[evidence,setEvidence]=useState(null),[busy,setBusy]=useState(false)
  const load=()=>Promise.all([societyWorkOrderAPI.list(),societyStaffAPI.getStaff(),societyAgencyAPI.list(),societyVendorAPI.getVendors(),expenseCategoryAPI.getCategories()]).then(([w,s,a,v,c])=>{setRows(w.data||[]);setStaff(s.data||[]);setAgencies(a.data||[]);setVendors(v.data||[]);setCategories((c.data||[]).filter(x=>x.categoryType==='SOCIETY_REGULAR'))}).catch(e=>toast.error(e.response?.data?.message||'Unable to load work orders'))
  useEffect(()=>{load()},[])
  const loadEvidence=async id=>setAttachments((await attachmentAPI.getAttachments('WORK_ORDER',id)).data||[])
  const loadExpenses=async id=>setExpenseRequests((await societyWorkOrderAPI.getExpenseRequests(id)).data||[])
  const open=async id=>{try{const [work]=await Promise.all([societyWorkOrderAPI.get(id),loadEvidence(id),loadExpenses(id)]);setSelected(work.data)}catch(e){toast.error(e.response?.data?.message||'Unable to open work order')}}
  const create=async e=>{e.preventDefault();setBusy(true);try{await societyWorkOrderAPI.create({...form,plannedStart:form.plannedStart||null,dueAt:form.dueAt||null,estimatedCost:form.estimatedCost===''?null:Number(form.estimatedCost),recurrenceType:form.recurrenceType||null,recurrenceInterval:form.recurrenceType?Number(form.recurrenceInterval||1):null,recurrenceEnd:form.recurrenceEnd||null});setForm(empty);toast.success('Work order created');load()}catch(x){toast.error(x.response?.data?.message||'Unable to create work order')}finally{setBusy(false)}}
  const act=async fn=>{try{const {data}=await fn();setSelected(data);load()}catch(e){toast.error(e.response?.data?.message||'Unable to update work order')}}
  const assign=()=>{if(!assignee)return;const [type,id]=assignee.split(':');act(()=>societyWorkOrderAPI.assign(selected.id,{staffId:type==='staff'?Number(id):null,agencyId:type==='agency'?Number(id):null,vendorId:type==='vendor'?Number(id):null}))}
  const progress=()=>{const notes=window.prompt('Progress notes:');if(!notes)return;const status=window.prompt('Status: IN_PROGRESS or BLOCKED','IN_PROGRESS');if(status)act(()=>societyWorkOrderAPI.update(selected.id,{notes,status:status.toUpperCase()}))}
  const complete=()=>{const completionNotes=window.prompt('Completion notes:');if(!completionNotes)return;const cost=window.prompt('Actual cost (optional):','');act(()=>societyWorkOrderAPI.complete(selected.id,{completionNotes,actualCost:cost?Number(cost):null}))}
  const review=verify=>{const notes=window.prompt(verify?'Verification notes (optional):':'Reason for reopening:','');act(()=>verify?societyWorkOrderAPI.verify(selected.id,{notes}):societyWorkOrderAPI.reopen(selected.id,{notes}))}
  const uploadEvidence=async e=>{e.preventDefault();if(!evidence)return;setBusy(true);try{await attachmentAPI.uploadAttachment('WORK_ORDER',selected.id,evidence);setEvidence(null);await loadEvidence(selected.id);toast.success('Evidence uploaded')}catch(x){toast.error(x.response?.data?.message||'Unable to upload evidence')}finally{setBusy(false)}}
  const openEvidence=async item=>{try{const response=await attachmentAPI.downloadAttachment(item.id);const url=URL.createObjectURL(new Blob([response.data],{type:item.fileType||'application/octet-stream'}));window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(x){toast.error(x.response?.data?.message||'Unable to open evidence')}}
  const removeEvidence=async id=>{if(!window.confirm('Delete this evidence file?'))return;try{await attachmentAPI.deleteAttachment(id);await loadEvidence(selected.id);toast.success('Evidence deleted')}catch(x){toast.error(x.response?.data?.message||'Unable to delete evidence')}}
  const requestExpense=async e=>{e.preventDefault();setBusy(true);try{await societyWorkOrderAPI.requestExpense(selected.id,{...expense,categoryId:Number(expense.categoryId),amount:Number(expense.amount)});setExpense({categoryId:'',amount:'',description:'',vendorName:''});await loadExpenses(selected.id);toast.success('Expense submitted for admin approval')}catch(x){toast.error(x.response?.data?.message||'Unable to request expense')}finally{setBusy(false)}}
  const active=rows.filter(x=>!['VERIFIED','CANCELLED'].includes(x.status)), overdue=rows.filter(x=>x.overdue)
  return <Shell title="Work Orders" eyebrow="Society operations"><SummaryGrid items={[["Open work",active.length],["Overdue",overdue.length],["Completed",rows.filter(x=>x.status==='COMPLETED').length],["Verified",rows.filter(x=>x.status==='VERIFIED').length]]}/><section className="report-panel"><h2>Recurrence for new work</h2><div className="form-grid"><label>Repeat<select value={form.recurrenceType} onChange={e=>setForm({...form,recurrenceType:e.target.value})}><option value="">One time</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option></select></label>{form.recurrenceType&&<><label>Every<input type="number" min="1" value={form.recurrenceInterval} onChange={e=>setForm({...form,recurrenceInterval:e.target.value})}/></label><label>Repeat until<input type="date" value={form.recurrenceEnd} onChange={e=>setForm({...form,recurrenceEnd:e.target.value})}/></label><p className="muted">The next occurrence is created after admin verification.</p></>}</div></section>
   <form className="form-panel" onSubmit={create}><h2>Create work order</h2><div className="form-grid"><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['ELECTRICAL','PLUMBING','LIFT','CLEANING','SECURITY','CIVIL','GARDENING','FIRE_SAFETY','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','NORMAL','HIGH','EMERGENCY'].map(x=><option key={x}>{x}</option>)}</select></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Planned start<input type="datetime-local" value={form.plannedStart} onChange={e=>setForm({...form,plannedStart:e.target.value})}/></label><label>Due at<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label>Estimated cost<input type="number" min="0" step="0.01" value={form.estimatedCost} onChange={e=>setForm({...form,estimatedCost:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="primary" disabled={busy}>Create work order</button></form>
   <div className="table-wrap"><table><thead><tr><th>Order</th><th>Work</th><th>Priority</th><th>Status</th><th>Assigned to</th><th>Due</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.workOrderNumber}</td><td><strong>{x.title}</strong><br/><small>{x.location||x.category}</small></td><td>{x.priority}</td><td><span className={`status-pill ${x.overdue?'rejected':x.status==='VERIFIED'?'approved':''}`}>{x.overdue?'OVERDUE':x.status}</span></td><td>{x.assignments?.map(a=>a.assigneeName).join(', ')||'-'}</td><td>{x.dueAt?new Date(x.dueAt).toLocaleString():'-'}</td><td><button onClick={()=>open(x.id)}>Open</button></td></tr>)}</tbody></table></div>
   {selected&&<section className="report-panel"><div className="section-heading-row"><div><h2>{selected.workOrderNumber} · {selected.title}</h2><p className="muted">{selected.description||'No description'} · {selected.status}</p></div><button onClick={()=>setSelected(null)}>Close</button></div>{!['VERIFIED','CANCELLED'].includes(selected.status)&&<div className="form-actions"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Assign to...</option><optgroup label="Staff">{staff.map(x=><option key={`s${x.id}`} value={`staff:${x.id}`}>{x.staffName}</option>)}</optgroup><optgroup label="Agencies">{agencies.map(x=><option key={`a${x.id}`} value={`agency:${x.id}`}>{x.name}</option>)}</optgroup><optgroup label="Vendors">{vendors.map(x=><option key={`v${x.id}`} value={`vendor:${x.id}`}>{x.supplierName}</option>)}</optgroup></select><button onClick={assign}>Assign</button><button onClick={progress}>Add progress</button><button className="primary" onClick={complete}>Complete</button></div>}{admin&&selected.status==='COMPLETED'&&<div className="form-actions"><button className="primary" onClick={()=>review(true)}>Verify</button><button onClick={()=>review(false)}>Reopen</button></div>}<h3>Evidence</h3>{!['VERIFIED','CANCELLED'].includes(selected.status)&&<form className="form-actions" onSubmit={uploadEvidence}><input aria-label="Evidence file" type="file" accept=".jpg,.jpeg,.jfif,.png,.pdf" onChange={e=>setEvidence(e.target.files?.[0]||null)}/><button className="primary" disabled={!evidence||busy}>Upload evidence</button></form>}<div className="table-actions">{attachments.map(item=><span key={item.id}><button onClick={()=>openEvidence(item)}>{item.fileName}</button>{!['VERIFIED','CANCELLED'].includes(selected.status)&&<button className="danger" aria-label={`Delete ${item.fileName}`} onClick={()=>removeEvidence(item.id)}>Delete</button>}</span>)}{!attachments.length&&<span className="muted">No evidence uploaded.</span>}</div><h3>Timeline</h3>{selected.updates?.map(x=><p key={x.id}><strong>{x.updateType}</strong> · {x.createdBy} · {new Date(x.createdAt).toLocaleString()}<br/><span className="muted">{x.notes}</span></p>)}</section>}
   {selected&&<section className="report-panel"><h3>Expense requests</h3>{!['VERIFIED','CANCELLED'].includes(selected.status)&&<form className="form-grid" onSubmit={requestExpense}><label>Category<select required value={expense.categoryId} onChange={e=>setExpense({...expense,categoryId:e.target.value})}><option value="">Select category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.categoryName}</option>)}</select></label><label>Amount<input required type="number" min="0.01" step="0.01" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Vendor<input value={expense.vendorName} onChange={e=>setExpense({...expense,vendorName:e.target.value})}/></label><label>Description<textarea required value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})}/></label><button className="primary" disabled={busy}>Request approval</button></form>}<div className="table-wrap"><table><thead><tr><th>Expense</th><th>Category</th><th>Description</th><th>Amount</th><th>Status</th></tr></thead><tbody>{expenseRequests.map(x=><tr key={x.id}><td>#{x.id}</td><td>{x.categoryName}</td><td>{x.description}</td><td>{Number(x.amount).toLocaleString(undefined,{style:'currency',currency:'INR'})}</td><td><span className={`status-pill ${x.status==='APPROVED'?'approved':x.status==='REJECTED'?'rejected':''}`}>{x.status}</span></td></tr>)}{!expenseRequests.length&&<tr><td colSpan="5" className="empty-state">No expense requests.</td></tr>}</tbody></table></div></section>}
  </Shell>
}
