import { useEffect, useMemo, useRef, useState } from 'react'
import { toast } from 'react-toastify'
import { expenseAPI, societyAnnualCollectionAPI, societyFlatAPI } from '../../../api/endpoints'
import { formatCurrency, formatDate } from '../../../utils/format'
import { Shell, SummaryGrid } from '../../DashboardRouter'
import { CollectionModal } from './CollectionModal'
import { ExpenseModal } from './ExpenseModal'
import { BankBookImportModal } from './BankBookImportModal'
import { useAuthStore } from '../../../store/authStore'

const currentFinancialYear=()=>{const d=new Date(),y=d.getMonth()<3?d.getFullYear()-1:d.getFullYear();return `${y}-${y+1}`}
const availableFinancialYears=()=>{const currentStart=Number(currentFinancialYear().slice(0,4));return Array.from({length:currentStart-2024+1},(_,index)=>{const start=currentStart-index;return `${start}-${start+1}`})}
export const AnnualFinance=()=>{
 const currentAccount=useAuthStore(state=>state.currentAccount),canWrite=currentAccount?.role!=='MEMBER'
 const [financialYear,setFinancialYear]=useState(currentFinancialYear()),[rows,setRows]=useState([]),[collectionTotal,setCollectionTotal]=useState(0),[collectionTotals,setCollectionTotals]=useState({totalCollected:0,maintenanceCollected:0}),[collectionsLoading,setCollectionsLoading]=useState(false),[flats,setFlats]=useState([]),[expenses,setExpenses]=useState([]),[activeView,setActiveView]=useState('overview'),[collectionSearch,setCollectionSearch]=useState(''),[collectionPage,setCollectionPage]=useState(1),[expensePage,setExpensePage]=useState(1),[modal,setModal]=useState(null)
 const collectionRequest=useRef(0)
 const loadCollections=()=>{const request=++collectionRequest.current;setCollectionsLoading(true);return societyAnnualCollectionAPI.list(financialYear,collectionPage-1,10,collectionSearch.trim()).then(r=>{if(request===collectionRequest.current){setRows(r.data?.content||[]);setCollectionTotal(Number(r.data?.totalElements||0))}}).catch(()=>{if(request===collectionRequest.current)toast.error('Unable to load collections')}).finally(()=>{if(request===collectionRequest.current)setCollectionsLoading(false)})}
 const loadCollectionTotals=()=>societyAnnualCollectionAPI.summary(financialYear).then(r=>setCollectionTotals(r.data||{})).catch(()=>toast.error('Unable to load collection totals'))
 const loadExpenses=()=>expenseAPI.getExpenses().then(r=>setExpenses(r.data||[])).catch(()=>toast.error('Unable to load expenses'))
 useEffect(()=>{loadCollectionTotals();loadExpenses();societyFlatAPI.getFlats().then(r=>setFlats(r.data||[])).catch(()=>{})},[financialYear])
 useEffect(()=>{if(activeView!=='collections')return;const timer=setTimeout(loadCollections,300);return()=>clearTimeout(timer)},[financialYear,collectionPage,collectionSearch,activeView])
 const totals={total:Number(collectionTotals.totalCollected||0),MAINTENANCE:Number(collectionTotals.maintenanceCollected||0)},yearStart=`${financialYear.slice(0,4)}-04-01`,yearEnd=`${financialYear.slice(5)}-03-31`
 const collectionPageCount=Math.max(1,Math.ceil(collectionTotal/10)),visibleCollections=rows
 const annualExpenses=useMemo(()=>expenses.filter(x=>x.expenseDate>=yearStart&&x.expenseDate<=yearEnd).sort((a,b)=>String(b.expenseDate).localeCompare(String(a.expenseDate))),[expenses,yearStart,yearEnd]),expenseTotal=annualExpenses.reduce((s,x)=>s+Number(x.amount||0),0),pageCount=Math.max(1,Math.ceil(annualExpenses.length/10)),visibleExpenses=annualExpenses.slice((expensePage-1)*10,expensePage*10)
 const remove=async id=>{if(!window.confirm('Delete this collection entry?'))return;try{await societyAnnualCollectionAPI.delete(id);toast.success('Collection deleted');if(rows.length===1&&collectionPage>1)setCollectionPage(page=>page-1);else loadCollections();loadCollectionTotals()}catch(error){toast.error(error.response?.data?.message||'Unable to delete collection')}}
 return <Shell title="Annual Finance" eyebrow="Society module" actions={canWrite&&<div className="table-actions"><button onClick={()=>setModal('bankBook')}>Import Cash / Bank Book</button><button onClick={()=>setModal('collection')}>Record Collection</button><button className="primary" onClick={()=>setModal('expense')}>Add Expense</button></div>}>
  <section className="toolbar-panel"><label>Financial year<select value={financialYear} onChange={e=>{setFinancialYear(e.target.value);setCollectionPage(1);setExpensePage(1)}}>{availableFinancialYears().map(year=><option key={year} value={year}>{year}{year===currentFinancialYear()?' (Current)':''}</option>)}</select></label></section>
  <div className="shared-expense-submenu">{['overview','collections','expenses'].map(x=><button key={x} className={activeView===x?'active':''} onClick={()=>setActiveView(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
  <SummaryGrid items={[[ 'Total received',formatCurrency(totals.total) ],[ 'Total expenses',formatCurrency(expenseTotal) ],[ 'Net balance',formatCurrency(totals.total-expenseTotal) ],[ 'Maintenance',formatCurrency(totals.MAINTENANCE||0) ]]}/>
  {activeView==='overview'&&<section className="report-panel"><h2>{financialYear} summary</h2><p className="muted">Collections and expenses from 1 April {financialYear.slice(0,4)} through 31 March {financialYear.slice(5)}.</p></section>}
  {activeView==='collections'&&<><section className="toolbar-panel"><input type="search" placeholder="Search flat, payer, reference or transaction" value={collectionSearch} onChange={e=>{setCollectionSearch(e.target.value);setCollectionPage(1)}}/><strong>{collectionTotal} found</strong></section><div className="table-wrap"><table className="annual-collections-table"><thead><tr><th>Date</th><th>Type</th><th>Flat</th><th>Source</th><th>Mode</th><th>Reference</th><th>Transaction ID</th><th>Settlement ID</th><th className="numeric">Amount</th>{canWrite&&<th>Action</th>}</tr></thead><tbody>{visibleCollections.map(x=><tr key={x.id}><td>{formatDate(x.paymentDate)}</td><td>{x.collectionType}</td><td>{x.flatLabel||'-'}</td><td>{x.sourceName}</td><td>{x.paymentMode}</td><td>{x.referenceNumber||'-'}</td><td>{x.transactionId||'-'}</td><td>{x.settlementId||'-'}</td><td className="numeric">{formatCurrency(x.amount)}</td>{canWrite&&<td className="table-actions"><button onClick={()=>setModal({type:'collection',item:x})}>Edit</button><button className="danger" onClick={()=>remove(x.id)}>Delete</button></td>}</tr>)}{!collectionsLoading&&!visibleCollections.length&&<tr><td colSpan={canWrite?10:9} className="empty-state">{collectionSearch.trim()?'No collections match your search.':'No collections recorded.'}</td></tr>}{collectionsLoading&&<tr><td colSpan={canWrite?10:9} className="empty-state">Loading collections...</td></tr>}</tbody></table></div>{collectionPageCount>1&&<nav className="table-pagination" aria-label="Collection pages"><button aria-label="First collection page" title="First page" disabled={collectionPage===1||collectionsLoading} onClick={()=>setCollectionPage(1)}>«</button><button aria-label="Previous collection page" title="Previous page" disabled={collectionPage===1||collectionsLoading} onClick={()=>setCollectionPage(page=>Math.max(1,page-1))}>‹</button><span>Page {collectionPage} of {collectionPageCount}</span><button aria-label="Next collection page" title="Next page" disabled={collectionPage===collectionPageCount||collectionsLoading} onClick={()=>setCollectionPage(page=>Math.min(collectionPageCount,page+1))}>›</button><button aria-label="Last collection page" title="Last page" disabled={collectionPage===collectionPageCount||collectionsLoading} onClick={()=>setCollectionPage(collectionPageCount)}>»</button></nav>}</>}
  {activeView==='expenses'&&<><div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Vendor</th><th>Payment</th><th>Status</th><th className="numeric">Amount</th>{canWrite&&<th>Action</th>}</tr></thead><tbody>{visibleExpenses.map(x=><tr key={x.id}><td>{formatDate(x.expenseDate)}</td><td>{x.categoryName||'-'}</td><td>{x.vendorName||'-'}</td><td>{x.paymentMode}</td><td><span className={`status-pill ${String(x.status).toLowerCase()}`}>{x.status}</span></td><td className="numeric">{formatCurrency(x.amount)}</td>{canWrite&&<td><button onClick={()=>setModal({type:'expense',item:x})}>Edit</button></td>}</tr>)}{!annualExpenses.length&&<tr><td colSpan={canWrite?7:6} className="empty-state">No expenses found.</td></tr>}</tbody></table></div>{pageCount>1&&<nav className="table-pagination" aria-label="Expense pages"><button aria-label="First expense page" title="First page" disabled={expensePage===1} onClick={()=>setExpensePage(1)}>«</button><button aria-label="Previous expense page" title="Previous page" disabled={expensePage===1} onClick={()=>setExpensePage(x=>Math.max(1,x-1))}>‹</button><span>Page {expensePage} of {pageCount}</span><button aria-label="Next expense page" title="Next page" disabled={expensePage===pageCount} onClick={()=>setExpensePage(x=>Math.min(pageCount,x+1))}>›</button><button aria-label="Last expense page" title="Last page" disabled={expensePage===pageCount} onClick={()=>setExpensePage(pageCount)}>»</button></nav>}</>}
  {canWrite&&<CollectionModal open={modal==='collection'||modal?.type==='collection'} collection={modal?.item} financialYear={financialYear} flats={flats} onClose={()=>setModal(null)} onSaved={()=>{loadCollections();loadCollectionTotals();setActiveView('collections')}}/>}
  {canWrite&&<ExpenseModal open={modal==='expense'||modal?.type==='expense'} expense={modal?.item} financialYear={financialYear} onClose={()=>setModal(null)} onSaved={()=>{loadExpenses();setActiveView('expenses')}}/>}
  {canWrite&&<BankBookImportModal open={modal==='bankBook'} financialYear={financialYear} flats={flats} onClose={()=>setModal(null)} onImported={()=>{setCollectionPage(1);loadCollections();loadCollectionTotals();setActiveView('collections')}}/>}
 </Shell>
}
